// AUTO-GENERATED by scripts/fetch-pricing.mjs — do not edit by hand.
// AWS Price List, us-east-1, on-demand. USD. Hourly unless noted.
export const PRICING_SNAPSHOT_DATE = "2026-06-27";

export const PRICES = {
  ec2HourlyByType: {
  "r8gb.medium": 0.09109,
  "x8g.8xlarge": 3.1264,
  "inf1.xlarge": 0.228,
  "r7g.12xlarge": 2.5704,
  "m8gb.12xlarge": 3.492,
  "c7gn.16xlarge": 3.9936,
  "r7gd.8xlarge": 2.1773,
  "g5.16xlarge": 4.096,
  "m6i.16xlarge": 3.072,
  "r6a.32xlarge": 7.2576,
  "m8gb.8xlarge": 2.328,
  "c8gd.medium": 0.04899,
  "r7iz.xlarge": 0.372,
  "c8gd.24xlarge": 4.70304,
  "m8id.8xlarge": 2.08832,
  "x1.32xlarge": 13.338,
  "m9gd.xlarge": 0.2514,
  "m7i-flex.2xlarge": 0.38304,
  "c7g.large": 0.0725,
  "c6a.12xlarge": 1.836,
  "c8gb.48xlarge": 11.376,
  "p5en.48xlarge": 0,
  "p6-b200.48xlarge": 0,
  "m6i.2xlarge": 0.384,
  "g7e.24xlarge": 16.57216,
  "m8idn.2xlarge": 0.76376,
  "z1d.large": 0.186,
  "r8ib.12xlarge": 5.0208,
  "r7iz.4xlarge": 1.488,
  "c7i.2xlarge": 0.357,
  "z1d.2xlarge": 0.744,
  "c8id.24xlarge": 5.32224,
  "g4dn.8xlarge": 2.176,
  "c5a.xlarge": 0.154,
  "c8ine.8xlarge": 2.7216,
  "m8id.48xlarge": 12.52992,
  "r6a.4xlarge": 0.9072,
  "dl1.24xlarge": 13.10904,
  "c8id.32xlarge": 7.09632,
  "m8gd.16xlarge": 3.69024,
  "c8id.96xlarge": 21.28896,
  "g6e.16xlarge": 7.57719,
  "r8idb.48xlarge": 22.50912,
  "c5a.8xlarge": 1.232,
  "c6gd.xlarge": 0.1536,
  "c8i.24xlarge": 4.49808,
  "r6idn.2xlarge": 0.78156,
  "i4g.8xlarge": 2.47104,
  "r7gd.4xlarge": 1.0886,
  "m5.xlarge": 0.192,
  "i4i.xlarge": 0.343,
  "r8i-flex.12xlarge": 3.16728,
  "r5dn.8xlarge": 2.672,
  "c6i.xlarge": 0.17,
  "r7i.48xlarge": 12.7008,
  "f1.16xlarge": 13.2,
  "c8gb.2xlarge": 0.474,
  "t4g.xlarge": 0.1344,
  "c6g.8xlarge": 1.088,
  "h1.4xlarge": 0.936,
  "m5n.4xlarge": 0.952,
  "r8g.8xlarge": 1.88512,
  "c6a.xlarge": 0.153,
  "i8ge.18xlarge": 8.5428,
  "c8g.large": 0.07976,
  "m6id.16xlarge": 3.7968,
  "m5zn.6xlarge": 1.982,
  "r7g.large": 0.1071,
  "m8idb.2xlarge": 0.76376,
  "r7a.medium": 0.07608,
  "r8idn.4xlarge": 1.87576,
  "t3.nano": 0.0052,
  "c8a.12xlarge": 2.58648,
  "m8idn.32xlarge": 12.22016,
  "p2.8xlarge": 7.2,
  "m5a.2xlarge": 0.344,
  "c6id.xlarge": 0.2016,
  "c7a.16xlarge": 3.28448,
  "m6a.xlarge": 0.1728,
  "r6gd.large": 0.1152,
  "i8ge.xlarge": 0.4746,
  "c7a.xlarge": 0.20528,
  "i4g.2xlarge": 0.61776,
  "r7gd.2xlarge": 0.5443,
  "hpc7g.8xlarge": 1.6832,
  "c8i.2xlarge": 0.37484,
  "m8i.large": 0.10584,
  "m8idb.48xlarge": 18.33024,
  "m8gb.48xlarge": 13.968,
  "r8gn.8xlarge": 2.9149,
  "m6gd.12xlarge": 2.1696,
  "z1d.12xlarge": 4.464,
  "m5dn.8xlarge": 2.176,
  "m6in.8xlarge": 2.22768,
  "r8gb.48xlarge": 17.48928,
  "r8gd.large": 0.14696,
  "r5b.12xlarge": 3.576,
  "m8gd.48xlarge": 11.07072,
  "c5ad.2xlarge": 0.344,
  "c6a.16xlarge": 2.448,
  "r5ad.16xlarge": 4.192,
  "r8i.96xlarge": 26.67264,
  "m5a.24xlarge": 4.128,
  "m7i-flex.12xlarge": 2.29824,
  "m6idn.2xlarge": 0.63648,
  "g4ad.8xlarge": 1.734,
  "i7i.large": 0.1888,
  "r8ib.xlarge": 0.4184,
  "x1e.16xlarge": 13.344,
  "r8idb.24xlarge": 11.25456,
  "m6i.12xlarge": 2.304,
  "p2.16xlarge": 14.4,
  "m8id.large": 0.13052,
  "m7gd.12xlarge": 2.5628,
  "r6i.large": 0.126,
  "m8ib.large": 0.16708,
  "r8id.12xlarge": 3.99168,
  "t3.2xlarge": 0.3328,
  "t3.large": 0.0832,
  "m8i.8xlarge": 1.69344,
  "c7i.xlarge": 0.1785,
  "m5ad.large": 0.103,
  "r8g.xlarge": 0.23564,
  "r7g.xlarge": 0.2142,
  "m6g.12xlarge": 1.848,
  "r6g.16xlarge": 3.2256,
  "c6in.xlarge": 0.2268,
  "c7i-flex.2xlarge": 0.33915,
  "m8in.2xlarge": 0.66832,
  "r5ad.large": 0.131,
  "m5a.12xlarge": 2.064,
  "i8ge.large": 0.2373,
  "x2iezn.6xlarge": 5.004,
  "r6i.12xlarge": 3.024,
  "c5n.4xlarge": 0.864,
  "m6a.24xlarge": 4.1472,
  "m8gn.4xlarge": 1.164,
  "r6in.32xlarge": 11.15712,
  "m8in.8xlarge": 2.67328,
  "inf1.24xlarge": 4.721,
  "c8gn.large": 0.1185,
  "z1d.6xlarge": 2.232,
  "g3.4xlarge": 1.14,
  "m6i.large": 0.096,
  "r7i.xlarge": 0.2646,
  "r8id.24xlarge": 7.98336,
  "m7i.8xlarge": 1.6128,
  "m8ib.32xlarge": 10.69312,
  "c6in.16xlarge": 3.6288,
  "m7g.8xlarge": 1.3056,
  "i8ge.6xlarge": 2.8476,
  "m8idb.4xlarge": 1.52752,
  "r4.large": 0.133,
  "c8gn.medium": 0.0593,
  "c5a.2xlarge": 0.308,
  "m8g.medium": 0.04488,
  "i8g.8xlarge": 2.7456,
  "i7ie.12xlarge": 6.2376,
  "c7g.4xlarge": 0.58,
  "c6g.large": 0.068,
  "r8gd.24xlarge": 7.05408,
  "d3en.12xlarge": 6.30864,
  "c7a.2xlarge": 0.41056,
  "r8a.xlarge": 0.31952,
  "m8in.24xlarge": 8.01984,
  "r6i.16xlarge": 4.032,
  "c7a.8xlarge": 1.64224,
  "c6in.8xlarge": 1.8144,
  "t3.medium": 0.0416,
  "m9gd.medium": 0.06285,
  "m8ine.xlarge": 0.4177,
  "r8gd.2xlarge": 0.58784,
  "x2iedn.32xlarge": 26.676,
  "m8a.large": 0.12172,
  "g5.12xlarge": 5.672,
  "r5n.xlarge": 0.298,
  "r7i.4xlarge": 1.0584,
  "c8id.large": 0.11088,
  "r6in.12xlarge": 4.18392,
  "m8gd.xlarge": 0.23064,
  "m8gd.24xlarge": 5.53536,
  "c7i-flex.xlarge": 0.16958,
  "r8i.24xlarge": 6.66816,
  "im4gn.8xlarge": 2.91034,
  "r6in.16xlarge": 5.57856,
  "c7gd.12xlarge": 2.1773,
  "r8in.2xlarge": 0.8368,
  "m7g.12xlarge": 1.9584,
  "r6idn.xlarge": 0.39078,
  "m8i.12xlarge": 2.54016,
  "m8gn.24xlarge": 6.984,
  "m6gd.8xlarge": 1.4464,
  "r8a.2xlarge": 0.63904,
  "is4gen.8xlarge": 4.6104,
  "r6id.12xlarge": 3.6288,
  "m8azn.3xlarge": 1.23876,
  "c7gd.medium": 0.0454,
  "m8i.xlarge": 0.21168,
  "r8gb.xlarge": 0.36436,
  "c8gn.24xlarge": 5.688,
  "r5n.2xlarge": 0.596,
  "c8i-flex.4xlarge": 0.71216,
  "t2.2xlarge": 0.3712,
  "i7i.8xlarge": 3.0202,
  "c5a.4xlarge": 0.616,
  "c6gn.8xlarge": 1.3824,
  "m6g.large": 0.077,
  "m9g.xlarge": 0.19568,
  "m8idb.12xlarge": 4.58256,
  "r4.2xlarge": 0.532,
  "r8i.12xlarge": 3.33408,
  "p5.48xlarge": 0,
  "r8gb.large": 0.18218,
  "x1e.32xlarge": 26.688,
  "r6id.24xlarge": 7.2576,
  "r8gd.xlarge": 0.29392,
  "m5n.16xlarge": 3.808,
  "g5g.xlarge": 0.42,
  "r6id.4xlarge": 1.2096,
  "c8gd.xlarge": 0.19596,
  "c8gn.12xlarge": 2.844,
  "i8ge.3xlarge": 1.4238,
  "gr6.4xlarge": 1.5392,
  "r5.4xlarge": 1.008,
  "c7gn.2xlarge": 0.4992,
  "r8a.16xlarge": 5.11232,
  "c8id.8xlarge": 1.77408,
  "r6id.2xlarge": 0.6048,
  "c8g.16xlarge": 2.55232,
  "g4ad.16xlarge": 3.468,
  "c8in.24xlarge": 6.53184,
  "r8gn.48xlarge": 17.4893,
  "m6g.xlarge": 0.154,
  "x8i.4xlarge": 1.75064,
  "r8gb.12xlarge": 4.37232,
  "c8gd.12xlarge": 2.35152,
  "c7i-flex.8xlarge": 1.3566,
  "r5n.4xlarge": 1.192,
  "c5.18xlarge": 3.06,
  "t4g.large": 0.0672,
  "r8gd.4xlarge": 1.17568,
  "c6gn.12xlarge": 2.0736,
  "x8g.48xlarge": 18.7584,
  "g6.48xlarge": 13.3504,
  "x2iezn.12xlarge": 10.008,
  "x8i.8xlarge": 3.50128,
  "m8i.4xlarge": 0.84672,
  "m6idn.16xlarge": 5.09184,
  "d3en.xlarge": 0.526,
  "m6in.16xlarge": 4.45536,
  "m8i-flex.2xlarge": 0.4022,
  "m8in.xlarge": 0.33416,
  "d3en.2xlarge": 1.051,
  "m8in.48xlarge": 16.03968,
  "m9gd.large": 0.1257,
  "c5d.9xlarge": 1.728,
  "c8id.16xlarge": 3.54816,
  "c5.24xlarge": 4.08,
  "m6a.48xlarge": 8.2944,
  "m6gd.xlarge": 0.1808,
  "h1.8xlarge": 1.872,
  "m7a.2xlarge": 0.46368,
  "x8g.4xlarge": 1.5632,
  "r8gn.large": 0.1822,
  "r5b.16xlarge": 4.768,
  "m5d.8xlarge": 1.808,
  "r7iz.large": 0.186,
  "im4gn.16xlarge": 5.82067,
  "x2iedn.24xlarge": 20.007,
  "u7i-12tb.224xlarge": 125.58182,
  "m9g.4xlarge": 0.78272,
  "r8idb.96xlarge": 45.01824,
  "r5.2xlarge": 0.504,
  "inf2.48xlarge": 12.98127,
  "m8in.16xlarge": 5.34656,
  "r5n.8xlarge": 2.384,
  "r7a.8xlarge": 2.4344,
  "c8gb.24xlarge": 5.688,
  "c6a.4xlarge": 0.612,
  "m6a.large": 0.0864,
  "c6id.8xlarge": 1.6128,
  "m6g.2xlarge": 0.308,
  "r8gn.medium": 0.0911,
  "vt1.24xlarge": 5.2,
  "r8g.medium": 0.05891,
  "g6.12xlarge": 4.6016,
  "r8in.4xlarge": 1.6736,
  "c7gn.large": 0.1248,
  "r5d.24xlarge": 6.912,
  "m8ib.2xlarge": 0.66832,
  "c7i.large": 0.08925,
  "c8gd.16xlarge": 3.13536,
  "m8i.2xlarge": 0.42336,
  "p6-b300.48xlarge": 0,
  "m8idb.32xlarge": 12.22016,
  "vt1.6xlarge": 1.3,
  "m6id.2xlarge": 0.4746,
  "c7g.2xlarge": 0.29,
  "m5ad.16xlarge": 3.296,
  "r4.8xlarge": 2.128,
  "c6in.12xlarge": 2.7216,
  "t2.large": 0.0928,
  "c8a.16xlarge": 3.44864,
  "i7i.16xlarge": 6.0403,
  "c7i.16xlarge": 2.856,
  "g5g.8xlarge": 1.372,
  "i3.16xlarge": 4.992,
  "r8i.2xlarge": 0.55568,
  "r5n.12xlarge": 3.576,
  "r7gd.16xlarge": 4.3546,
  "m8ib.48xlarge": 16.03968,
  "t4g.micro": 0.0084,
  "c6gn.medium": 0.0432,
  "g6.24xlarge": 6.6752,
  "m8a.2xlarge": 0.48688,
  "g5.8xlarge": 2.448,
  "r8g.large": 0.11782,
  "c8ib.4xlarge": 1.08864,
  "m5ad.xlarge": 0.206,
  "c7g.12xlarge": 1.74,
  "c7gd.xlarge": 0.1814,
  "i7ie.48xlarge": 24.9504,
  "m6id.24xlarge": 5.6952,
  "c8gb.16xlarge": 3.792,
  "g5.4xlarge": 1.624,
  "i4g.16xlarge": 4.94208,
  "c7a.24xlarge": 4.92672,
  "r7i.large": 0.1323,
  "m8ib.4xlarge": 1.33664,
  "m6idn.4xlarge": 1.27296,
  "r6in.4xlarge": 1.39464,
  "g5g.16xlarge": 2.744,
  "g3.8xlarge": 2.28,
  "c8ib.large": 0.13608,
  "r6gd.12xlarge": 2.7648,
  "r7iz.12xlarge": 4.464,
  "m7a.32xlarge": 7.41888,
  "x2gd.12xlarge": 4.008,
  "r8ib.48xlarge": 20.0832,
  "r7a.24xlarge": 7.3032,
  "m9gd.2xlarge": 0.5028,
  "r5n.24xlarge": 7.152,
  "gr6f.4xlarge": 1.066,
  "c8i.96xlarge": 17.99232,
  "r8id.32xlarge": 10.64448,
  "r8i-flex.xlarge": 0.26394,
  "p4d.24xlarge": 0,
  "c6gd.4xlarge": 0.6144,
  "c8gn.xlarge": 0.237,
  "r5ad.4xlarge": 1.048,
  "c7gd.8xlarge": 1.4515,
  "m7a.12xlarge": 2.78208,
  "m8id.12xlarge": 3.13248,
  "m5dn.16xlarge": 4.352,
  "r5b.large": 0.149,
  "r5ad.24xlarge": 6.288,
  "r6idn.4xlarge": 1.56312,
  "is4gen.2xlarge": 1.1526,
  "m5dn.4xlarge": 1.088,
  "m8idn.12xlarge": 4.58256,
  "c5n.18xlarge": 3.888,
  "z1d.3xlarge": 1.116,
  "c8in.96xlarge": 26.12736,
  "r6gd.xlarge": 0.2304,
  "i7ie.24xlarge": 12.4752,
  "c6g.xlarge": 0.136,
  "x2gd.xlarge": 0.334,
  "r8ib.large": 0.2092,
  "x8g.large": 0.1954,
  "t4g.small": 0.0168,
  "m5ad.12xlarge": 2.472,
  "m8g.8xlarge": 1.43616,
  "is4gen.large": 0.28815,
  "x8i.32xlarge": 14.00512,
  "c8i.16xlarge": 2.99872,
  "m8g.xlarge": 0.17952,
  "d3en.6xlarge": 3.154,
  "r8gd.16xlarge": 4.70272,
  "c7g.8xlarge": 1.16,
  "r8in.32xlarge": 13.3888,
  "m8gb.16xlarge": 4.656,
  "r6idn.32xlarge": 12.50496,
  "i8ge.12xlarge": 5.6952,
  "g7e.12xlarge": 8.28608,
  "c5a.large": 0.077,
  "m8gb.24xlarge": 6.984,
  "r8i.8xlarge": 2.22272,
  "u7in-32tb.224xlarge": 360.98695,
  "r7gd.medium": 0.068,
  "c7i-flex.12xlarge": 2.0349,
  "g5g.2xlarge": 0.556,
  "c8g.medium": 0.03988,
  "r8id.2xlarge": 0.66528,
  "r8g.24xlarge": 5.65536,
  "c6gn.16xlarge": 2.7648,
  "t2.medium": 0.0464,
  "p5.4xlarge": 0,
  "r6id.large": 0.1512,
  "c5d.12xlarge": 2.304,
  "g4ad.2xlarge": 0.54117,
  "m5.24xlarge": 4.608,
  "m6id.12xlarge": 2.8476,
  "r6a.xlarge": 0.2268,
  "inf2.xlarge": 0.7582,
  "r6in.8xlarge": 2.78928,
  "i3en.12xlarge": 5.424,
  "c8ine.xlarge": 0.3402,
  "r8gb.24xlarge": 8.74464,
  "trn1.2xlarge": 1.34375,
  "m6gd.4xlarge": 0.7232,
  "m9gd.4xlarge": 1.0056,
  "gr6.8xlarge": 2.4464,
  "t2.xlarge": 0.1856,
  "g4dn.4xlarge": 1.204,
  "r8idn.8xlarge": 3.75152,
  "r8i.xlarge": 0.27784,
  "g6e.2xlarge": 2.24208,
  "t3.xlarge": 0.1664,
  "m5ad.24xlarge": 4.944,
  "c8ib.16xlarge": 4.35456,
  "i4g.4xlarge": 1.23552,
  "m8azn.xlarge": 0.41292,
  "m8ine.2xlarge": 0.8354,
  "m7a.4xlarge": 0.92736,
  "m8i-flex.12xlarge": 2.4132,
  "r8id.96xlarge": 31.93344,
  "r8a.48xlarge": 15.33696,
  "m8g.24xlarge": 4.30848,
  "c7i.4xlarge": 0.714,
  "inf2.8xlarge": 1.96786,
  "c7gd.16xlarge": 2.903,
  "m6a.16xlarge": 2.7648,
  "t3a.nano": 0.0047,
  "m5zn.large": 0.1652,
  "x8i.64xlarge": 28.01024,
  "m7g.medium": 0.0408,
  "m6in.32xlarge": 8.91072,
  "m5a.large": 0.086,
  "m8gd.4xlarge": 0.92256,
  "r8gd.8xlarge": 2.35136,
  "r8gn.12xlarge": 4.3723,
  "c7a.32xlarge": 6.56896,
  "c4.2xlarge": 0.398,
  "r8idn.32xlarge": 15.00608,
  "m5.2xlarge": 0.384,
  "c6id.large": 0.1008,
  "i4i.large": 0.172,
  "c7gd.2xlarge": 0.3629,
  "m8id.96xlarge": 25.05984,
  "c7a.4xlarge": 0.82112,
  "c6g.4xlarge": 0.544,
  "r5d.16xlarge": 4.608,
  "c8i.4xlarge": 0.74968,
  "r6i.24xlarge": 6.048,
  "m8idn.xlarge": 0.38188,
  "r7i.12xlarge": 3.1752,
  "is4gen.xlarge": 0.5763,
  "c8gb.12xlarge": 2.844,
  "r7a.16xlarge": 4.8688,
  "r6in.2xlarge": 0.69732,
  "p2.xlarge": 0.9,
  "r8a.12xlarge": 3.83424,
  "r8gn.24xlarge": 8.7446,
  "g6e.xlarge": 1.861,
  "x8g.24xlarge": 9.3792,
  "m8gd.8xlarge": 1.84512,
  "m6in.2xlarge": 0.55692,
  "m7i.24xlarge": 4.8384,
  "r5a.2xlarge": 0.452,
  "r6i.2xlarge": 0.504,
  "c6gd.medium": 0.0384,
  "g3s.xlarge": 0.75,
  "r6g.medium": 0.0504,
  "c6gn.2xlarge": 0.3456,
  "m8id.xlarge": 0.26104,
  "m8id.32xlarge": 8.35328,
  "m5d.large": 0.113,
  "m8idn.8xlarge": 3.05504,
  "m6id.xlarge": 0.2373,
  "r5a.12xlarge": 2.712,
  "m6id.8xlarge": 1.8984,
  "c5a.12xlarge": 1.848,
  "d3.xlarge": 0.499,
  "c8i-flex.xlarge": 0.17804,
  "i8g.4xlarge": 1.3728,
  "c5ad.4xlarge": 0.688,
  "m8in.32xlarge": 10.69312,
  "r8i-flex.16xlarge": 4.22304,
  "m6g.16xlarge": 2.464,
  "i4i.8xlarge": 2.746,
  "c8gd.48xlarge": 9.40608,
  "m6gd.large": 0.0904,
  "m7i-flex.large": 0.09576,
  "m9g.large": 0.09784,
  "hpc7g.16xlarge": 1.6832,
  "m6in.12xlarge": 3.34152,
  "c8i.32xlarge": 5.99744,
  "c8i.large": 0.09371,
  "m6idn.xlarge": 0.31824,
  "r5dn.2xlarge": 0.668,
  "m8gb.large": 0.1455,
  "c6i.4xlarge": 0.68,
  "m6a.4xlarge": 0.6912,
  "x2iezn.8xlarge": 6.672,
  "r5.24xlarge": 6.048,
  "r8id.48xlarge": 15.96672,
  "c5n.large": 0.108,
  "c8a.8xlarge": 1.72432,
  "c5ad.8xlarge": 1.376,
  "m8gn.medium": 0.0728,
  "c6id.4xlarge": 0.8064,
  "i3.2xlarge": 0.624,
  "m5n.8xlarge": 1.904,
  "c6i.large": 0.085,
  "r5.16xlarge": 4.032,
  "x8i.2xlarge": 0.87532,
  "m5a.xlarge": 0.172,
  "m5.12xlarge": 2.304,
  "r8i.32xlarge": 8.89088,
  "g4dn.12xlarge": 3.912,
  "p3.2xlarge": 3.06,
  "m8gn.xlarge": 0.291,
  "i8g.large": 0.1716,
  "g5.xlarge": 1.006,
  "m8ib.24xlarge": 8.01984,
  "m5ad.4xlarge": 0.824,
  "m7g.large": 0.0816,
  "r8i.4xlarge": 1.11136,
  "r6a.48xlarge": 10.8864,
  "c8in.12xlarge": 3.26592,
  "t3a.large": 0.0752,
  "r6a.large": 0.1134,
  "c8i-flex.8xlarge": 1.42432,
  "i8g.16xlarge": 5.4912,
  "x2iedn.4xlarge": 3.3345,
  "c8g.4xlarge": 0.63808,
  "m8id.16xlarge": 4.17664,
  "i8ge.48xlarge": 22.7808,
  "c5ad.12xlarge": 2.064,
  "im4gn.4xlarge": 1.45517,
  "c5.12xlarge": 2.04,
  "c8id.12xlarge": 2.66112,
  "g6f.2xlarge": 0.475,
  "c6gn.xlarge": 0.1728,
  "c8g.48xlarge": 7.65696,
  "c7a.12xlarge": 2.46336,
  "i7i.2xlarge": 0.755,
  "m4.large": 0.1,
  "r7i.2xlarge": 0.5292,
  "m5d.16xlarge": 3.616,
  "r6g.large": 0.1008,
  "r5dn.24xlarge": 8.016,
  "c8i.12xlarge": 2.24904,
  "u7in-24tb.224xlarge": 270.73128,
  "p3.16xlarge": 24.48,
  "m6id.32xlarge": 7.5936,
  "c8id.4xlarge": 0.88704,
  "m8i-flex.xlarge": 0.2011,
  "x2iedn.8xlarge": 6.669,
  "r8gd.12xlarge": 3.52704,
  "x8i.12xlarge": 5.25192,
  "c8ib.8xlarge": 2.17728,
  "m8i-flex.4xlarge": 0.8044,
  "r8gb.16xlarge": 5.82976,
  "f2.12xlarge": 3.96,
  "r7a.12xlarge": 3.6516,
  "r7gd.12xlarge": 3.2659,
  "g6f.xlarge": 0.2375,
  "m8i.32xlarge": 6.77376,
  "m7a.48xlarge": 11.12832,
  "r5.large": 0.126,
  "m5d.xlarge": 0.226,
  "r6idn.12xlarge": 4.68936,
  "m6in.large": 0.13923,
  "hpc7g.4xlarge": 1.6832,
  "r6i.32xlarge": 8.064,
  "r6a.2xlarge": 0.4536,
  "r6in.large": 0.17433,
  "c8in.4xlarge": 1.08864,
  "m6idn.8xlarge": 2.54592,
  "m7i.2xlarge": 0.4032,
  "r7a.4xlarge": 1.2172,
  "m6in.24xlarge": 6.68304,
  "m7i.12xlarge": 2.4192,
  "m8i-flex.8xlarge": 1.6088,
  "r5d.xlarge": 0.288,
  "m9gd.48xlarge": 12.0672,
  "m4.16xlarge": 3.2,
  "c7gd.4xlarge": 0.7258,
  "m9g.12xlarge": 2.34816,
  "m6g.4xlarge": 0.616,
  "m8in.4xlarge": 1.33664,
  "r5b.2xlarge": 0.596,
  "m9gd.8xlarge": 2.0112,
  "r5dn.xlarge": 0.334,
  "m5dn.xlarge": 0.272,
  "i7ie.6xlarge": 3.1188,
  "i8g.2xlarge": 0.6864,
  "m5n.2xlarge": 0.476,
  "p3dn.24xlarge": 31.212,
  "g7e.48xlarge": 33.14432,
  "m8gd.2xlarge": 0.46128,
  "c5.9xlarge": 1.53,
  "r8idn.16xlarge": 7.50304,
  "m8g.4xlarge": 0.71808,
  "x8g.16xlarge": 6.2528,
  "g4dn.16xlarge": 4.352,
  "r8idn.96xlarge": 45.01824,
  "r6in.xlarge": 0.34866,
  "r7g.16xlarge": 3.4272,
  "r6g.4xlarge": 0.8064,
  "g4dn.2xlarge": 0.752,
  "m8idb.96xlarge": 36.66048,
  "r5b.xlarge": 0.298,
  "c8a.2xlarge": 0.43108,
  "g6e.24xlarge": 15.06559,
  "m7a.xlarge": 0.23184,
  "r6gd.2xlarge": 0.4608,
  "r5dn.4xlarge": 1.336,
  "r8in.12xlarge": 5.0208,
  "h1.2xlarge": 0.468,
  "r7iz.16xlarge": 5.952,
  "r6id.8xlarge": 2.4192,
  "c5.xlarge": 0.17,
  "g6e.48xlarge": 30.13118,
  "r5n.large": 0.149,
  "g4ad.4xlarge": 0.867,
  "r8idn.xlarge": 0.46894,
  "c6g.16xlarge": 2.176,
  "r5dn.16xlarge": 5.344,
  "m9gd.12xlarge": 3.0168,
  "m8gd.medium": 0.05766,
  "i7ie.2xlarge": 1.0396,
  "c8ine.12xlarge": 4.0824,
  "c5.4xlarge": 0.68,
  "c5ad.xlarge": 0.172,
  "c7gn.medium": 0.0624,
  "m8ib.96xlarge": 32.07936,
  "c6i.16xlarge": 2.72,
  "c6gd.12xlarge": 1.8432,
  "r8gd.medium": 0.07348,
  "g4dn.xlarge": 0.526,
  "c6id.16xlarge": 3.2256,
  "i4i.24xlarge": 8.2368,
  "m8idn.4xlarge": 1.52752,
  "r5.8xlarge": 2.016,
  "r8ib.24xlarge": 10.0416,
  "r7iz.8xlarge": 2.976,
  "m8azn.6xlarge": 2.47752,
  "g6.2xlarge": 0.9776,
  "m8azn.12xlarge": 4.95504,
  "m5dn.2xlarge": 0.544,
  "x2gd.large": 0.167,
  "c7a.48xlarge": 9.85344,
  "r8idb.large": 0.23447,
  "x1e.xlarge": 0.834,
  "d3en.8xlarge": 4.20576,
  "c8in.16xlarge": 4.35456,
  "m7a.large": 0.11592,
  "m8g.12xlarge": 2.15424,
  "t4g.medium": 0.0336,
  "m8a.48xlarge": 11.68512,
  "c6i.24xlarge": 4.08,
  "m4.4xlarge": 0.8,
  "is4gen.medium": 0.14408,
  "m5.8xlarge": 1.536,
  "c8in.8xlarge": 2.17728,
  "c7g.16xlarge": 2.32,
  "m7gd.medium": 0.0534,
  "c6in.32xlarge": 7.2576,
  "c6gn.4xlarge": 0.6912,
  "g6e.8xlarge": 4.52856,
  "r8id.8xlarge": 2.66112,
  "c8id.2xlarge": 0.44352,
  "r7g.8xlarge": 1.7136,
  "r6i.8xlarge": 2.016,
  "x8i.48xlarge": 21.00768,
  "r6id.16xlarge": 4.8384,
  "r5.xlarge": 0.252,
  "c5ad.24xlarge": 4.128,
  "d3.8xlarge": 3.99552,
  "c7gn.4xlarge": 0.9984,
  "m7i.xlarge": 0.2016,
  "r7g.2xlarge": 0.4284,
  "m8gn.large": 0.1455,
  "c6a.48xlarge": 7.344,
  "g3.16xlarge": 4.56,
  "i4i.12xlarge": 4.118,
  "t3a.2xlarge": 0.3008,
  "m6i.8xlarge": 1.536,
  "c8a.4xlarge": 0.86216,
  "c4.8xlarge": 1.591,
  "i3.large": 0.156,
  "i7i.24xlarge": 9.0605,
  "r5ad.xlarge": 0.262,
  "r4.xlarge": 0.266,
  "m7gd.xlarge": 0.2136,
  "im4gn.xlarge": 0.36379,
  "m7a.8xlarge": 1.85472,
  "c8id.xlarge": 0.22176,
  "r5b.4xlarge": 1.192,
  "r8idb.16xlarge": 7.50304,
  "m8g.48xlarge": 8.61696,
  "c8gd.8xlarge": 1.56768,
  "m8i.48xlarge": 10.16064,
  "c8ine.4xlarge": 1.3608,
  "m5n.large": 0.119,
  "m6i.xlarge": 0.192,
  "r8gb.2xlarge": 0.72872,
  "c6i.32xlarge": 5.44,
  "m8azn.24xlarge": 9.91008,
  "m6a.32xlarge": 5.5296,
  "r8a.medium": 0.07988,
  "m8id.24xlarge": 6.26496,
  "c6in.4xlarge": 0.9072,
  "r8in.16xlarge": 6.6944,
  "t3.small": 0.0208,
  "x8i.large": 0.21883,
  "im4gn.2xlarge": 0.72758,
  "c6a.24xlarge": 3.672,
  "m8azn.medium": 0.10323,
  "c8gb.8xlarge": 1.896,
  "m6in.4xlarge": 1.11384,
  "m7g.2xlarge": 0.3264,
  "inf2.24xlarge": 6.49063,
  "r8in.24xlarge": 10.0416,
  "i3.xlarge": 0.312,
  "c7i-flex.large": 0.08479,
  "m5.4xlarge": 0.768,
  "m8ib.16xlarge": 5.34656,
  "c7g.medium": 0.0363,
  "m8a.12xlarge": 2.92128,
  "x8i.96xlarge": 48.74438,
  "c8gn.2xlarge": 0.474,
  "r8i.large": 0.13892,
  "trn1.32xlarge": 21.5,
  "m5d.4xlarge": 0.904,
  "c4.4xlarge": 0.796,
  "c8gb.4xlarge": 0.948,
  "m5.large": 0.096,
  "c8ib.96xlarge": 26.12736,
  "c5n.2xlarge": 0.432,
  "c8g.24xlarge": 3.82848,
  "i4i.4xlarge": 1.373,
  "m7a.16xlarge": 3.70944,
  "r8a.24xlarge": 7.66848,
  "r8idb.2xlarge": 0.93788,
  "m7i-flex.4xlarge": 0.76608,
  "r8ib.16xlarge": 6.6944,
  "c7i.24xlarge": 4.284,
  "r5d.2xlarge": 0.576,
  "m4.10xlarge": 2,
  "r8gn.2xlarge": 0.7287,
  "r5a.8xlarge": 1.808,
  "r8idb.32xlarge": 15.00608,
  "m7g.xlarge": 0.1632,
  "m9g.8xlarge": 1.56544,
  "m7gd.2xlarge": 0.4271,
  "m8azn.large": 0.20646,
  "m5d.12xlarge": 2.712,
  "c7gn.12xlarge": 2.9952,
  "c6id.2xlarge": 0.4032,
  "i3en.xlarge": 0.452,
  "t4g.nano": 0.0042,
  "i3.4xlarge": 1.248,
  "r8id.4xlarge": 1.33056,
  "r6id.xlarge": 0.3024,
  "i7ie.18xlarge": 9.3564,
  "m6g.medium": 0.0385,
  "c4.xlarge": 0.199,
  "p3.8xlarge": 12.24,
  "i3en.6xlarge": 2.712,
  "c8ib.2xlarge": 0.54432,
  "r6idn.16xlarge": 6.25248,
  "m8g.16xlarge": 2.87232,
  "m8i-flex.large": 0.10055,
  "i8ge.24xlarge": 11.3904,
  "m8idn.48xlarge": 18.33024,
  "x1e.8xlarge": 6.672,
  "c8id.48xlarge": 10.64448,
  "m6i.32xlarge": 6.144,
  "m8idb.large": 0.19094,
  "c8a.xlarge": 0.21554,
  "m5n.24xlarge": 5.712,
  "c8in.48xlarge": 13.06368,
  "u7i-6tb.112xlarge": 62.79,
  "x2idn.16xlarge": 6.669,
  "i8g.24xlarge": 8.2368,
  "c7a.medium": 0.05132,
  "c8i-flex.16xlarge": 2.84864,
  "c7g.xlarge": 0.145,
  "g5.2xlarge": 1.212,
  "r6g.12xlarge": 2.4192,
  "x8i.xlarge": 0.43766,
  "m7g.4xlarge": 0.6528,
  "c8g.xlarge": 0.15952,
  "m5zn.xlarge": 0.3303,
  "m7i.large": 0.1008,
  "i3.8xlarge": 2.496,
  "r6idn.24xlarge": 9.37872,
  "r7a.48xlarge": 14.6064,
  "m8i.96xlarge": 20.32128,
  "x2iezn.2xlarge": 1.668,
  "m7i.16xlarge": 3.2256,
  "m7a.24xlarge": 5.56416,
  "c8i.48xlarge": 8.99616,
  "r8idn.24xlarge": 11.25456,
  "r6g.2xlarge": 0.4032,
  "c7i.48xlarge": 8.568,
  "m6gd.16xlarge": 2.8928,
  "m5dn.12xlarge": 3.264,
  "c8ib.32xlarge": 8.70912,
  "m8a.4xlarge": 0.97376,
  "c6a.large": 0.0765,
  "f1.4xlarge": 3.3,
  "r6i.xlarge": 0.252,
  "r8idn.large": 0.23447,
  "g7e.8xlarge": 5.26824,
  "r8gb.4xlarge": 1.45744,
  "r8ib.4xlarge": 1.6736,
  "x2iedn.2xlarge": 1.66725,
  "c8i.xlarge": 0.18742,
  "z1d.xlarge": 0.372,
  "t3a.small": 0.0188,
  "r8a.4xlarge": 1.27808,
  "r8id.xlarge": 0.33264,
  "m9gd.16xlarge": 4.0224,
  "x1e.2xlarge": 1.668,
  "c5n.xlarge": 0.216,
  "m8idn.large": 0.19094,
  "r6id.32xlarge": 9.6768,
  "m5a.8xlarge": 1.376,
  "r8g.12xlarge": 2.82768,
  "d3.2xlarge": 0.999,
  "r5d.4xlarge": 1.152,
  "i7i.12xlarge": 4.5302,
  "m5a.16xlarge": 2.752,
  "r8ib.96xlarge": 40.1664,
  "r8g.48xlarge": 11.31072,
  "r5d.8xlarge": 2.304,
  "r7gd.large": 0.1361,
  "r8idn.2xlarge": 0.93788,
  "x8g.2xlarge": 0.7816,
  "c6gd.large": 0.0768,
  "m5n.12xlarge": 2.856,
  "m6idn.12xlarge": 3.81888,
  "i4g.xlarge": 0.30888,
  "x8g.xlarge": 0.3908,
  "r8g.2xlarge": 0.47128,
  "c6in.large": 0.1134,
  "c8gn.48xlarge": 11.376,
  "c8a.48xlarge": 10.34592,
  "g4ad.xlarge": 0.37853,
  "r5ad.12xlarge": 3.144,
  "u7i-8tb.112xlarge": 83.72,
  "inf1.6xlarge": 1.18,
  "r8id.large": 0.16632,
  "g6.4xlarge": 1.3232,
  "m6in.xlarge": 0.27846,
  "r7iz.32xlarge": 11.904,
  "r7g.4xlarge": 0.8568,
  "r5d.large": 0.144,
  "p4de.24xlarge": 27.44705,
  "m6g.8xlarge": 1.232,
  "m7i.4xlarge": 0.8064,
  "x2gd.8xlarge": 2.672,
  "m8gd.large": 0.11532,
  "i7ie.xlarge": 0.5198,
  "c6gd.2xlarge": 0.3072,
  "g5g.4xlarge": 0.828,
  "m7gd.large": 0.1068,
  "r8ib.8xlarge": 3.3472,
  "u-6tb1.56xlarge": 46.40391,
  "t3a.xlarge": 0.1504,
  "m8gb.xlarge": 0.291,
  "r6a.16xlarge": 3.6288,
  "m8gn.8xlarge": 2.328,
  "t3a.medium": 0.0376,
  "t2.micro": 0.0116,
  "c8i-flex.2xlarge": 0.35608,
  "t4g.2xlarge": 0.2688,
  "c5d.2xlarge": 0.384,
  "c8i.8xlarge": 1.49936,
  "m7gd.8xlarge": 1.7086,
  "c7gn.8xlarge": 1.9968,
  "m8a.medium": 0.06086,
  "r5n.16xlarge": 4.768,
  "m5zn.2xlarge": 0.6607,
  "r8g.4xlarge": 0.94256,
  "m6id.4xlarge": 0.9492,
  "c5.large": 0.085,
  "m8gb.medium": 0.07275,
  "u-6tb1.112xlarge": 54.6,
  "r8idb.4xlarge": 1.87576,
  "m9g.24xlarge": 4.69632,
  "r5dn.large": 0.167,
  "c6g.medium": 0.034,
  "c6gd.16xlarge": 2.4576,
  "r8i.16xlarge": 4.44544,
  "r6g.8xlarge": 1.6128,
  "m7a.medium": 0.05796,
  "c5d.xlarge": 0.192,
  "m8gb.2xlarge": 0.582,
  "m6idn.32xlarge": 10.18368,
  "i3en.large": 0.226,
  "m6i.24xlarge": 4.608,
  "r4.4xlarge": 1.064,
  "i8g.12xlarge": 4.1184,
  "r6idn.large": 0.19539,
  "c7a.large": 0.10264,
  "r8idb.12xlarge": 5.62728,
  "m8in.96xlarge": 32.07936,
  "c8a.24xlarge": 5.17296,
  "d3.4xlarge": 1.998,
  "r4.16xlarge": 4.256,
  "g6e.4xlarge": 3.00424,
  "r5b.24xlarge": 7.152,
  "x2idn.24xlarge": 10.0035,
  "m6id.large": 0.11865,
  "c8i-flex.12xlarge": 2.13648,
  "r6gd.medium": 0.0576,
  "i7ie.large": 0.2599,
  "r5d.12xlarge": 3.456,
  "r7a.32xlarge": 9.7376,
  "r5a.large": 0.113,
  "m7i-flex.8xlarge": 1.53216,
  "h1.16xlarge": 3.744,
  "m8a.xlarge": 0.24344,
  "c8gb.xlarge": 0.237,
  "r8in.8xlarge": 3.3472,
  "c6gn.large": 0.0864,
  "r6in.24xlarge": 8.36784,
  "r7i.8xlarge": 2.1168,
  "r5.12xlarge": 3.024,
  "m8gn.2xlarge": 0.582,
  "is4gen.4xlarge": 2.3052,
  "x2iezn.4xlarge": 3.336,
  "c7i.8xlarge": 1.428,
  "m6a.2xlarge": 0.3456,
  "g6.16xlarge": 3.3968,
  "c6id.24xlarge": 4.8384,
  "m5zn.3xlarge": 0.991,
  "c6in.2xlarge": 0.4536,
  "c8ine.large": 0.1701,
  "m8a.8xlarge": 1.94752,
  "m8ine.large": 0.20885,
  "t3a.micro": 0.0094,
  "c8ib.12xlarge": 3.26592,
  "c5d.large": 0.096,
  "c8g.12xlarge": 1.91424,
  "m8i-flex.16xlarge": 3.2176,
  "c6g.12xlarge": 1.632,
  "c6gd.8xlarge": 1.2288,
  "i4i.16xlarge": 5.491,
  "x8i.16xlarge": 7.00256,
  "c5ad.large": 0.086,
  "r7a.large": 0.15215,
  "m8gn.48xlarge": 13.968,
  "c5n.9xlarge": 1.944,
  "r8idn.12xlarge": 5.62728,
  "c6i.8xlarge": 1.36,
  "c8a.large": 0.10777,
  "c8gb.medium": 0.05925,
  "g6.8xlarge": 2.0144,
  "x2gd.medium": 0.0835,
  "i7i.48xlarge": 18.121,
  "r8gn.16xlarge": 5.8298,
  "m6gd.medium": 0.0452,
  "m5.16xlarge": 3.072,
  "m8a.24xlarge": 5.84256,
  "u-3tb1.56xlarge": 27.3,
  "m4.2xlarge": 0.4,
  "c7i-flex.4xlarge": 0.6783,
  "r8i-flex.8xlarge": 2.11152,
  "m8i.24xlarge": 5.08032,
  "c8gn.16xlarge": 3.792,
  "c8g.2xlarge": 0.31904,
  "i3en.24xlarge": 10.848,
  "m8ib.12xlarge": 4.00992,
  "r8i-flex.2xlarge": 0.52788,
  "t2.small": 0.023,
  "m8ib.xlarge": 0.33416,
  "m5a.4xlarge": 0.688,
  "m8i.16xlarge": 3.38688,
  "c8ine.2xlarge": 0.6804,
  "r6gd.8xlarge": 1.8432,
  "r8idb.8xlarge": 3.75152,
  "g5.24xlarge": 8.144,
  "i8ge.2xlarge": 0.9492,
  "m7gd.16xlarge": 3.4171,
  "c6a.2xlarge": 0.306,
  "f2.48xlarge": 15.84,
  "r5a.24xlarge": 5.424,
  "r8id.16xlarge": 5.32224,
  "m8ib.8xlarge": 2.67328,
  "m5ad.2xlarge": 0.412,
  "g7e.4xlarge": 3.99816,
  "m6a.8xlarge": 1.3824,
  "c8in.xlarge": 0.27216,
  "m9g.2xlarge": 0.39136,
  "m8in.12xlarge": 4.00992,
  "t2.nano": 0.0058,
  "r8gd.48xlarge": 14.10816,
  "r8ib.32xlarge": 13.3888,
  "c5d.4xlarge": 0.768,
  "i7i.4xlarge": 1.5101,
  "r6a.8xlarge": 1.8144,
  "c5ad.16xlarge": 2.752,
  "m6idn.24xlarge": 7.63776,
  "m5ad.8xlarge": 1.648,
  "i7ie.3xlarge": 1.5594,
  "m5zn.12xlarge": 3.9641,
  "m8id.4xlarge": 1.04416,
  "im4gn.large": 0.1819,
  "x2gd.16xlarge": 5.344,
  "c5d.24xlarge": 4.608,
  "r8in.96xlarge": 40.1664,
  "c7i.12xlarge": 2.142,
  "m8idb.xlarge": 0.38188,
  "m7i-flex.16xlarge": 3.06432,
  "r6a.24xlarge": 5.4432,
  "g6.xlarge": 0.8048,
  "c5a.16xlarge": 2.464,
  "i3en.3xlarge": 1.356,
  "x2idn.32xlarge": 13.338,
  "c8in.2xlarge": 0.54432,
  "r7gd.xlarge": 0.2722,
  "m8idb.24xlarge": 9.16512,
  "c8ib.xlarge": 0.27216,
  "r7a.2xlarge": 0.6086,
  "r5a.4xlarge": 0.904,
  "m4.xlarge": 0.2,
  "c8a.medium": 0.05389,
  "c8gd.4xlarge": 0.78384,
  "r6gd.16xlarge": 3.6864,
  "r8idn.48xlarge": 22.50912,
  "r5dn.12xlarge": 4.008,
  "c4.large": 0.1,
  "inf1.2xlarge": 0.362,
  "f2.6xlarge": 1.98,
  "m8id.2xlarge": 0.52208,
  "m9g.medium": 0.04892,
  "m8idn.24xlarge": 9.16512,
  "m7i.48xlarge": 9.6768,
  "x2iedn.xlarge": 0.83363,
  "r8i-flex.large": 0.13197,
  "c7gn.xlarge": 0.2496,
  "m6gd.2xlarge": 0.3616,
  "r5a.16xlarge": 3.616,
  "m8idn.96xlarge": 36.66048,
  "c6id.12xlarge": 2.4192,
  "r7a.xlarge": 0.3043,
  "c6g.2xlarge": 0.272,
  "r8ib.2xlarge": 0.8368,
  "i8g.xlarge": 0.3432,
  "r5b.8xlarge": 2.384,
  "x2gd.2xlarge": 0.668,
  "c8gb.large": 0.1185,
  "r5ad.8xlarge": 2.096,
  "c6a.32xlarge": 4.896,
  "c7i-flex.16xlarge": 2.7132,
  "c8i-flex.large": 0.08902,
  "c8gd.2xlarge": 0.39192,
  "vt1.3xlarge": 0.65,
  "c6i.12xlarge": 2.04,
  "r6idn.8xlarge": 3.12624,
  "x1e.4xlarge": 3.336,
  "r8a.8xlarge": 2.55616,
  "c5a.24xlarge": 3.696,
  "c7gd.large": 0.0907,
  "m8ine.8xlarge": 3.3416,
  "r8gn.4xlarge": 1.4574,
  "r8a.large": 0.15976,
  "c8gn.4xlarge": 0.948,
  "r7g.medium": 0.0536,
  "m9g.16xlarge": 3.13088,
  "g6f.large": 0.202,
  "r7i.16xlarge": 4.2336,
  "r8in.48xlarge": 20.0832,
  "r6a.12xlarge": 2.7216,
  "m8a.16xlarge": 3.89504,
  "g6e.12xlarge": 10.49264,
  "m5dn.large": 0.136,
  "m5dn.24xlarge": 6.528,
  "m8ine.12xlarge": 5.0124,
  "r8g.16xlarge": 3.77024,
  "c8gd.large": 0.09798,
  "m5d.2xlarge": 0.452,
  "x8i.24xlarge": 10.50384,
  "c6i.2xlarge": 0.34,
  "x2iedn.16xlarge": 13.338,
  "m8g.large": 0.08976,
  "r8idb.xlarge": 0.46894,
  "m8g.2xlarge": 0.35904,
  "m8idb.16xlarge": 6.11008,
  "x8g.12xlarge": 4.6896,
  "m6a.12xlarge": 2.0736,
  "m6i.4xlarge": 0.768,
  "m8gb.4xlarge": 1.164,
  "m5d.24xlarge": 5.424,
  "x1.16xlarge": 6.669,
  "m5n.xlarge": 0.238,
  "r6i.4xlarge": 1.008,
  "r8in.xlarge": 0.4184,
  "i8g.48xlarge": 16.4736,
  "m8gd.12xlarge": 2.76768,
  "m8in.large": 0.16708,
  "c6in.24xlarge": 5.4432,
  "i7i.xlarge": 0.3775,
  "m6idn.large": 0.15912,
  "i4i.32xlarge": 10.9824,
  "m8idb.8xlarge": 3.05504,
  "x8g.medium": 0.0977,
  "u7in-16tb.224xlarge": 180.47558,
  "f1.2xlarge": 1.65,
  "g5.48xlarge": 16.288,
  "i4i.2xlarge": 0.686,
  "r6g.xlarge": 0.2016,
  "m7i-flex.xlarge": 0.19152,
  "i4g.large": 0.15444,
  "m8idn.16xlarge": 6.11008,
  "m8gn.12xlarge": 3.492,
  "r6gd.4xlarge": 0.9216,
  "c8g.8xlarge": 1.27616,
  "r7iz.2xlarge": 0.744,
  "x2gd.4xlarge": 1.336,
  "d3en.4xlarge": 2.103,
  "r7i.24xlarge": 6.3504,
  "c8ib.24xlarge": 6.53184,
  "g6f.4xlarge": 0.95,
  "c5.2xlarge": 0.34,
  "r8i-flex.4xlarge": 1.05576,
  "m7g.16xlarge": 2.6112,
  "c6id.32xlarge": 6.4512,
  "t3.micro": 0.0104,
  "r5a.xlarge": 0.226,
  "m9gd.24xlarge": 6.0336,
  "m8gn.16xlarge": 4.656,
  "r8i.48xlarge": 13.33632,
  "r8gb.8xlarge": 2.91488,
  "m7gd.4xlarge": 0.8543,
  "c5d.18xlarge": 3.456,
  "m8ine.4xlarge": 1.6708,
  "c8ib.48xlarge": 13.06368,
  "g7e.2xlarge": 3.36312,
  "c8in.large": 0.13608,
  "c6a.8xlarge": 1.224,
  "r8gn.xlarge": 0.3644,
  "r8in.large": 0.2092,
  "i3en.2xlarge": 0.904,
  "c8in.32xlarge": 8.70912,
  "m9g.48xlarge": 9.39264,
  "trn1n.32xlarge": 24.78,
  "c8gn.8xlarge": 1.896,
  "r5ad.2xlarge": 0.524
} as Record<string, number>,
  rdsHourlyByClassEngine: {
  "db.x2iedn.2xlarge": {
    "SQL Server": 6.7766,
    "MySQL": 3.804,
    "MariaDB": 3.804,
    "Oracle": 3.804,
    "Db2": 3.804,
    "PostgreSQL": 3.804
  },
  "db.t3.xlarge": {
    "Oracle": 0.272,
    "SQL Server": 0.4,
    "Db2": 0.29,
    "PostgreSQL": 0.29,
    "MySQL": 0.272,
    "MariaDB": 0.272
  },
  "db.r5.2xlarge": {
    "Aurora MySQL": 1.508,
    "Aurora PostgreSQL": 1.16,
    "SQL Server": 5.002,
    "Oracle": 1.928,
    "Oracle (on-premises for Outposts)": 0.496,
    "MySQL (on-premise for Outpost)": 0.456,
    "SQL Server (on-premise for Outpost)": 2.536,
    "MySQL": 0.96,
    "MariaDB": 0.96,
    "PostgreSQL (on-premise for Outpost)": 0.496,
    "PostgreSQL": 1
  },
  "db.m7i.48xlarge": {
    "Db2": 17.088,
    "MySQL": 17.088,
    "Oracle (on-premises for Outposts)": 9.5232,
    "PostgreSQL (on-premise for Outpost)": 7.872,
    "SQL Server": 17.088,
    "MariaDB": 17.088,
    "PostgreSQL": 17.088,
    "Oracle": 17.088
  },
  "db.r5b.2xlarge.tpc2.mem4x": {
    "Oracle": 4.41
  },
  "db.r5.large": {
    "Aurora MySQL": 0.29,
    "Aurora PostgreSQL": 0.377,
    "Oracle (on-premises for Outposts)": 0.124,
    "Oracle": 0.233,
    "SQL Server": 1.02,
    "MySQL": 0.24,
    "MariaDB": 0.24,
    "PostgreSQL": 0.25,
    "SQL Server (on-premise for Outpost)": 0.334,
    "PostgreSQL (on-premise for Outpost)": 0.124,
    "MySQL (on-premise for Outpost)": 0.114
  },
  "db.r6i.8xlarge": {
    "SQL Server": 5.952,
    "MySQL": 3.84,
    "Aurora MySQL": 4.64,
    "Aurora PostgreSQL": 4.64,
    "Db2": 4,
    "MariaDB": 3.84,
    "PostgreSQL": 4,
    "Oracle": 3.728
  },
  "db.r7i.24xlarge": {
    "SQL Server": 12,
    "Aurora MySQL": 18.096,
    "PostgreSQL": 12,
    "MySQL": 12,
    "Oracle (on-premises for Outposts)": 6.2496,
    "MariaDB": 12,
    "Aurora PostgreSQL": 13.92,
    "Db2": 12,
    "PostgreSQL (on-premise for Outpost)": 5.952,
    "Oracle": 12
  },
  "db.r6g.large": {
    "Aurora PostgreSQL": 0.338,
    "MariaDB": 0.215,
    "Aurora MySQL": 0.338,
    "PostgreSQL": 0.225,
    "MySQL": 0.215
  },
  "db.r5.24xlarge": {
    "SQL Server (on-premise for Outpost)": 53.976,
    "PostgreSQL (on-premise for Outpost)": 5.952,
    "Aurora PostgreSQL": 18.096,
    "Aurora MySQL": 18.096,
    "MySQL (on-premise for Outpost)": 5.472,
    "Oracle (on-premises for Outposts)": 5.952,
    "MySQL": 11.52,
    "SQL Server": 36.48,
    "Oracle": 11.184,
    "MariaDB": 11.52,
    "PostgreSQL": 12
  },
  "db.m6i.32xlarge": {
    "MariaDB": 10.944,
    "Db2": 11.392,
    "Oracle": 10.944,
    "SQL Server": 74.752,
    "MySQL": 10.944,
    "PostgreSQL": 11.392
  },
  "db.r7i.large": {
    "Aurora PostgreSQL": 0.29,
    "SQL Server": 0.25,
    "Oracle": 0.25,
    "Db2": 0.25,
    "MySQL": 0.25,
    "Aurora MySQL": 0.29,
    "Oracle (on-premises for Outposts)": 0.1302,
    "MariaDB": 0.25,
    "MySQL (on-premise for Outpost)": 0.124,
    "PostgreSQL (on-premise for Outpost)": 0.124,
    "PostgreSQL": 0.25
  },
  "db.m6in.12xlarge": {
    "PostgreSQL": 6.197,
    "MySQL": 6.197,
    "MariaDB": 6.197,
    "Db2": 6.197,
    "Oracle": 6.192
  },
  "db.r6idn.24xlarge": {
    "MariaDB": 18.608,
    "Db2": 18.608,
    "MySQL": 18.608,
    "PostgreSQL": 18.608
  },
  "db.r8a.8xlarge": {
    "SQL Server": 4.6037
  },
  "db.m6idn.24xlarge": {
    "Db2": 14.16,
    "PostgreSQL": 14.16,
    "MySQL": 14.16,
    "MariaDB": 14.16
  },
  "db.r6in.24xlarge": {
    "PostgreSQL": 16.603,
    "MariaDB": 16.603,
    "Db2": 16.603,
    "MySQL": 16.603,
    "Oracle": 16.608
  },
  "db.r7i.2xlarge": {
    "MySQL (on-premise for Outpost)": 0.496,
    "Db2": 1,
    "SQL Server": 1,
    "Oracle (on-premises for Outposts)": 0.5208,
    "MariaDB": 1,
    "PostgreSQL (on-premise for Outpost)": 0.496,
    "Aurora MySQL": 1.16,
    "Oracle": 1,
    "Aurora PostgreSQL": 1.16,
    "PostgreSQL": 1,
    "MySQL": 1
  },
  "db.r6id.large": {
    "Oracle": 0.298,
    "MariaDB": 0.298,
    "PostgreSQL": 0.298,
    "MySQL": 0.298
  },
  "db.r8i.xlarge": {
    "SQL Server": 0.5,
    "Oracle": 0.53
  },
  "db.m6idn.xlarge": {
    "MySQL": 0.59,
    "Db2": 0.59,
    "MariaDB": 0.59,
    "PostgreSQL": 0.59
  },
  "db.r5d.2xlarge": {
    "MariaDB": 1.143,
    "SQL Server": 5.127,
    "Oracle": 1.065,
    "MySQL": 1.143,
    "PostgreSQL": 1.143
  },
  "db.m5.12xlarge": {
    "Oracle (on-premises for Outposts)": 2.268,
    "SQL Server": 28.032,
    "SQL Server (on-premise for Outpost)": 25.728,
    "Oracle": 4.104,
    "PostgreSQL": 4.272,
    "MySQL (on-premise for Outpost)": 1.8,
    "PostgreSQL (on-premise for Outpost)": 1.968,
    "MySQL": 4.104,
    "MariaDB": 4.104
  },
  "db.t3.2xlarge": {
    "Db2": 0.579,
    "PostgreSQL": 0.579,
    "Oracle": 0.544,
    "MySQL": 0.544,
    "SQL Server": 4.524,
    "MariaDB": 0.544
  },
  "db.m7g.large": {
    "PostgreSQL": 0.168,
    "MySQL": 0.168,
    "MariaDB": 0.168
  },
  "db.m7i.xlarge": {
    "MySQL (on-premise for Outpost)": 0.164,
    "SQL Server": 0.356,
    "Oracle (on-premises for Outposts)": 0.1984,
    "MySQL": 0.356,
    "PostgreSQL": 0.356,
    "Oracle": 0.356,
    "Db2": 0.356,
    "MariaDB": 0.356,
    "PostgreSQL (on-premise for Outpost)": 0.164
  },
  "db.r6gd.4xlarge": {
    "Aurora PostgreSQL": 3.245,
    "PostgreSQL": 2.057,
    "MySQL": 2.057,
    "MariaDB": 2.057
  },
  "db.m6idn.2xlarge": {
    "PostgreSQL": 1.18,
    "Db2": 1.18,
    "MariaDB": 1.18,
    "MySQL": 1.18
  },
  "db.r6id.4xlarge": {
    "MariaDB": 2.386,
    "Oracle": 2.384,
    "PostgreSQL": 2.386,
    "MySQL": 2.386
  },
  "db.m6in.large": {
    "Db2": 0.258,
    "Oracle": 0.258,
    "MySQL": 0.258,
    "MariaDB": 0.258,
    "PostgreSQL": 0.258
  },
  "db.r6idn.8xlarge": {
    "Db2": 6.203,
    "PostgreSQL": 6.203,
    "MariaDB": 6.203,
    "MySQL": 6.203
  },
  "db.m6g.12xlarge": {
    "PostgreSQL": 3.816,
    "MariaDB": 3.648,
    "MySQL": 3.648
  },
  "db.r5b.large": {
    "Oracle": 0.276,
    "SQL Server": 0.541,
    "MySQL": 0.296,
    "MariaDB": 0.296,
    "PostgreSQL": 0.296
  },
  "db.m6i.12xlarge": {
    "Oracle": 4.104,
    "SQL Server": 28.032,
    "Db2": 4.272,
    "PostgreSQL": 4.272,
    "MySQL": 4.104,
    "MariaDB": 4.104
  },
  "db.m8i.24xlarge": {
    "SQL Server": 8.544,
    "Oracle": 8.97
  },
  "db.r8g.large": {
    "Aurora PostgreSQL": 0.276,
    "Aurora MySQL": 0.276,
    "MySQL": 0.239,
    "PostgreSQL": 0.239,
    "MariaDB": 0.239
  },
  "db.r6in.xlarge": {
    "Db2": 0.692,
    "MariaDB": 0.692,
    "Oracle": 0.692,
    "MySQL": 0.692,
    "PostgreSQL": 0.692
  },
  "db.r5d.xlarge": {
    "SQL Server": 0.945,
    "Oracle": 0.533,
    "PostgreSQL": 0.571,
    "MariaDB": 0.571,
    "MySQL": 0.571
  },
  "db.m7i.16xlarge": {
    "SQL Server": 5.696,
    "MariaDB": 5.696,
    "Oracle": 5.696,
    "Db2": 5.696,
    "Oracle (on-premises for Outposts)": 3.1744,
    "PostgreSQL": 5.696,
    "MySQL": 5.696,
    "PostgreSQL (on-premise for Outpost)": 2.624
  },
  "db.m5.2xlarge": {
    "Oracle (on-premises for Outposts)": 0.378,
    "SQL Server": 2.548,
    "SQL Server (on-premise for Outpost)": 0.718,
    "Oracle": 0.684,
    "PostgreSQL": 0.712,
    "MySQL": 0.684,
    "MariaDB": 0.684,
    "PostgreSQL (on-premise for Outpost)": 0.328,
    "MySQL (on-premise for Outpost)": 0.3
  },
  "db.z1d.6xlarge": {
    "SQL Server": 10.256,
    "Oracle": 4.104
  },
  "db.r6gd.2xlarge": {
    "MySQL": 1.029,
    "PostgreSQL": 1.029,
    "Aurora PostgreSQL": 1.248,
    "MariaDB": 1.029
  },
  "db.m6i.xlarge": {
    "PostgreSQL": 0.356,
    "SQL Server": 2.336,
    "Db2": 0.356,
    "MySQL": 0.342,
    "Oracle": 0.342,
    "MariaDB": 0.342
  },
  "db.r5b.4xlarge": {
    "PostgreSQL": 2.368,
    "SQL Server": 6.349,
    "MariaDB": 2.368,
    "Oracle": 2.205,
    "MySQL": 2.368
  },
  "db.r6g.2xlarge": {
    "MySQL": 0.859,
    "Aurora MySQL": 1.349,
    "Aurora PostgreSQL": 1.038,
    "MariaDB": 0.859,
    "PostgreSQL": 0.899
  },
  "db.r7g.large": {
    "PostgreSQL": 0.239,
    "Aurora MySQL": 0.276,
    "MariaDB": 0.239,
    "Aurora PostgreSQL": 0.276,
    "MySQL": 0.239
  },
  "db.r5.4xlarge": {
    "Aurora PostgreSQL": 2.32,
    "SQL Server (on-premise for Outpost)": 5.072,
    "PostgreSQL": 2,
    "Aurora MySQL": 2.32,
    "MySQL (on-premise for Outpost)": 0.912,
    "Oracle": 1.864,
    "Oracle (on-premises for Outposts)": 0.992,
    "PostgreSQL (on-premise for Outpost)": 0.992,
    "SQL Server": 6.08,
    "MySQL": 1.92,
    "MariaDB": 1.92
  },
  "db.m6g.large": {
    "MariaDB": 0.152,
    "MySQL": 0.152,
    "PostgreSQL": 0.159
  },
  "db.r5b.2xlarge.tpc1.mem2x": {
    "Oracle": 2.205
  },
  "db.m8i.xlarge": {
    "SQL Server": 0.356,
    "Oracle": 0.37
  },
  "db.m6id.xlarge": {
    "MySQL": 0.448,
    "MariaDB": 0.448,
    "Oracle": 0.448,
    "PostgreSQL": 0.448
  },
  "db.m9g.48xlarge": {
    "MySQL": 17.58,
    "PostgreSQL": 17.58,
    "MariaDB": 17.58
  },
  "db.m6id.32xlarge": {
    "Oracle": 14.336,
    "MariaDB": 14.349,
    "MySQL": 14.349,
    "PostgreSQL": 14.349
  },
  "db.m6in.xlarge": {
    "Db2": 0.516,
    "PostgreSQL": 0.516,
    "MySQL": 0.516,
    "Oracle": 0.516,
    "MariaDB": 0.516
  },
  "db.t3.small": {
    "Aurora MySQL": 0.041,
    "Db2": 0.036,
    "SQL Server": 0.044,
    "MariaDB": 0.034,
    "Oracle": 0.075,
    "MySQL": 0.034,
    "PostgreSQL": 0.036
  },
  "db.m6i.2xlarge": {
    "Db2": 0.712,
    "SQL Server": 1.2,
    "MySQL": 0.684,
    "Oracle": 0.684,
    "PostgreSQL": 0.712,
    "MariaDB": 0.684
  },
  "db.m9g.24xlarge": {
    "MariaDB": 8.79,
    "PostgreSQL": 8.79,
    "MySQL": 8.79
  },
  "db.r7i.xlarge": {
    "Oracle": 0.5,
    "PostgreSQL": 0.5,
    "Db2": 0.5,
    "SQL Server": 0.5,
    "Aurora PostgreSQL": 0.58,
    "Oracle (on-premises for Outposts)": 0.2604,
    "MySQL (on-premise for Outpost)": 0.248,
    "MariaDB": 0.5,
    "Aurora MySQL": 0.58,
    "MySQL": 0.5,
    "PostgreSQL (on-premise for Outpost)": 0.248
  },
  "db.r6i.large": {
    "SQL Server": 0.46,
    "Oracle": 0.482,
    "MariaDB": 0.24,
    "Aurora PostgreSQL": 0.29,
    "Db2": 0.25,
    "Aurora MySQL": 0.377,
    "MySQL": 0.24,
    "PostgreSQL": 0.25
  },
  "db.m5d.8xlarge": {
    "SQL Server": 19.1,
    "MariaDB": 3.352,
    "PostgreSQL": 3.352,
    "Oracle": 3.22,
    "MySQL": 3.352
  },
  "db.m5.4xlarge": {
    "MySQL": 1.368,
    "Oracle": 3.504,
    "SQL Server (on-premise for Outpost)": 8.577,
    "Oracle (on-premises for Outposts)": 0.756,
    "MariaDB": 1.368,
    "SQL Server": 2.247,
    "PostgreSQL": 1.424,
    "MySQL (on-premise for Outpost)": 0.6,
    "PostgreSQL (on-premise for Outpost)": 0.656
  },
  "db.r6g.12xlarge": {
    "Aurora PostgreSQL": 8.098,
    "Aurora MySQL": 8.098,
    "MariaDB": 5.155,
    "PostgreSQL": 5.395,
    "MySQL": 5.155
  },
  "db.r8i.48xlarge": {
    "SQL Server": 24,
    "Oracle": 25.2
  },
  "db.m6idn.large": {
    "MySQL": 0.295,
    "Db2": 0.295,
    "MariaDB": 0.295,
    "PostgreSQL": 0.295
  },
  "db.x2m.8xlarge": {
    "SQL Server": 15.216
  },
  "db.r5d.4xlarge": {
    "SQL Server": 3.777,
    "MariaDB": 2.286,
    "MySQL": 2.286,
    "Oracle": 2.131,
    "PostgreSQL": 2.286
  },
  "db.m8g.4xlarge": {
    "MySQL": 1.344,
    "PostgreSQL": 1.344,
    "MariaDB": 1.344
  },
  "db.r8gd.2xlarge": {
    "Aurora PostgreSQL": 1.6224,
    "MySQL": 1.092,
    "PostgreSQL": 1.092,
    "MariaDB": 1.092
  },
  "db.r5b.24xlarge": {
    "MySQL": 14.208,
    "SQL Server": 61.838,
    "PostgreSQL": 14.208,
    "Oracle": 13.231,
    "MariaDB": 14.208
  },
  "db.m7i.large": {
    "Oracle (on-premises for Outposts)": 0.0992,
    "SQL Server": 0.178,
    "Db2": 0.178,
    "MySQL": 0.178,
    "Oracle": 0.178,
    "PostgreSQL": 0.178,
    "PostgreSQL (on-premise for Outpost)": 0.082,
    "MariaDB": 0.178,
    "MySQL (on-premise for Outpost)": 0.082
  },
  "db.r5.xlarge": {
    "MariaDB": 0.48,
    "SQL Server (on-premise for Outpost)": 0.628,
    "Aurora MySQL": 0.754,
    "Oracle": 0.964,
    "Oracle (on-premises for Outposts)": 0.248,
    "PostgreSQL (on-premise for Outpost)": 0.248,
    "MySQL": 0.48,
    "Aurora PostgreSQL": 0.58,
    "MySQL (on-premise for Outpost)": 0.228,
    "PostgreSQL": 0.5,
    "SQL Server": 0.88
  },
  "db.m5d.xlarge": {
    "SQL Server": 1.291,
    "MariaDB": 0.419,
    "Oracle": 0.403,
    "MySQL": 0.419,
    "PostgreSQL": 0.419
  },
  "db.r8g.4xlarge": {
    "PostgreSQL": 1.912,
    "Aurora PostgreSQL": 2.208,
    "Aurora MySQL": 2.208,
    "MySQL": 1.912,
    "MariaDB": 1.912
  },
  "db.m5.xlarge": {
    "Oracle": 0.342,
    "MySQL (on-premise for Outpost)": 0.15,
    "PostgreSQL": 0.356,
    "Oracle (on-premises for Outposts)": 0.189,
    "SQL Server (on-premise for Outpost)": 1.032,
    "SQL Server": 1.224,
    "MySQL": 0.342,
    "MariaDB": 0.342,
    "PostgreSQL (on-premise for Outpost)": 0.164
  },
  "db.m5d.large": {
    "SQL Server": 0.341,
    "Oracle": 0.201,
    "MySQL": 0.21,
    "PostgreSQL": 0.21,
    "MariaDB": 0.21
  },
  "db.r6gd.16xlarge": {
    "PostgreSQL": 8.229,
    "MySQL": 8.229,
    "MariaDB": 8.229,
    "Aurora PostgreSQL": 9.984
  },
  "db.r8i.4xlarge": {
    "SQL Server": 2,
    "Oracle": 2.1
  },
  "db.m5d.12xlarge": {
    "MariaDB": 5.028,
    "SQL Server": 28.65,
    "Oracle": 4.83,
    "PostgreSQL": 5.028,
    "MySQL": 5.028
  },
  "db.r6idn.4xlarge": {
    "Db2": 3.101,
    "PostgreSQL": 3.101,
    "MariaDB": 3.101,
    "MySQL": 3.101
  },
  "db.r6i.32xlarge": {
    "SQL Server": 80.032,
    "Aurora MySQL": 24.128,
    "Aurora PostgreSQL": 18.56,
    "Db2": 16,
    "PostgreSQL": 16,
    "MariaDB": 15.36,
    "Oracle": 14.912,
    "MySQL": 15.36
  },
  "db.t4g.2xlarge": {
    "MySQL": 0.517,
    "MariaDB": 0.517,
    "PostgreSQL": 0.517
  },
  "db.m8gd.large": {
    "MySQL": 0.1976,
    "PostgreSQL": 0.1976,
    "MariaDB": 0.1976
  },
  "db.r5.12xlarge": {
    "MariaDB": 5.76,
    "SQL Server (on-premise for Outpost)": 15.216,
    "Aurora PostgreSQL": 9.048,
    "PostgreSQL": 6,
    "PostgreSQL (on-premise for Outpost)": 2.976,
    "MySQL": 5.76,
    "Oracle (on-premises for Outposts)": 2.976,
    "Aurora MySQL": 9.048,
    "MySQL (on-premise for Outpost)": 2.736,
    "SQL Server": 18.24,
    "Oracle": 5.592
  },
  "db.r8i.16xlarge": {
    "SQL Server": 8,
    "Oracle": 8.4
  },
  "db.r5d.16xlarge": {
    "MySQL": 9.143,
    "SQL Server": 41.018,
    "PostgreSQL": 9.143,
    "MariaDB": 9.143,
    "Oracle": 8.522
  },
  "db.m6in.2xlarge": {
    "PostgreSQL": 1.033,
    "Oracle": 1.032,
    "Db2": 1.032,
    "MariaDB": 1.033,
    "MySQL": 1.033
  },
  "db.r8i.32xlarge": {
    "SQL Server": 16,
    "Oracle": 16.8
  },
  "db.r7g.16xlarge": {
    "Aurora MySQL": 8.844,
    "PostgreSQL": 7.65,
    "MariaDB": 7.65,
    "Aurora PostgreSQL": 11.497,
    "MySQL": 7.65
  },
  "db.m8i.2xlarge": {
    "SQL Server": 0.712,
    "Oracle": 0.75
  },
  "db.r6i.16xlarge": {
    "MySQL": 7.68,
    "SQL Server": 11.904,
    "Aurora MySQL": 12.064,
    "Aurora PostgreSQL": 9.28,
    "Db2": 8,
    "MariaDB": 7.68,
    "PostgreSQL": 8,
    "Oracle": 7.456
  },
  "db.r8a.xlarge": {
    "SQL Server": 0.5754
  },
  "db.m9g.large": {
    "PostgreSQL": 0.183,
    "MariaDB": 0.183,
    "MySQL": 0.183
  },
  "db.m7i.8xlarge": {
    "Db2": 2.848,
    "Oracle (on-premises for Outposts)": 1.5872,
    "SQL Server": 2.848,
    "Oracle": 2.848,
    "PostgreSQL": 2.848,
    "MySQL": 2.848,
    "PostgreSQL (on-premise for Outpost)": 1.312,
    "MariaDB": 2.848,
    "MySQL (on-premise for Outpost)": 1.312
  },
  "db.m8i.12xlarge": {
    "SQL Server": 4.272,
    "Oracle": 4.49
  },
  "db.r7i.4xlarge": {
    "Oracle (on-premises for Outposts)": 1.0416,
    "MySQL (on-premise for Outpost)": 0.992,
    "SQL Server": 2,
    "Aurora PostgreSQL": 2.32,
    "Aurora MySQL": 3.016,
    "MariaDB": 2,
    "Db2": 2,
    "PostgreSQL": 2,
    "PostgreSQL (on-premise for Outpost)": 0.992,
    "Oracle": 2,
    "MySQL": 2
  },
  "db.x2idn.metal": {
    "Oracle": 16.8
  },
  "db.m6idn.12xlarge": {
    "Db2": 7.08,
    "MariaDB": 7.08,
    "MySQL": 7.08,
    "PostgreSQL": 7.08
  },
  "db.t4g.xlarge": {
    "MySQL": 0.258,
    "PostgreSQL": 0.258,
    "MariaDB": 0.258
  },
  "db.m9g.xlarge": {
    "PostgreSQL": 0.366,
    "MariaDB": 0.366,
    "MySQL": 0.366
  },
  "db.m5d.24xlarge": {
    "MySQL": 10.057,
    "MariaDB": 10.057,
    "PostgreSQL": 10.057,
    "SQL Server": 57.3,
    "Oracle": 9.661
  },
  "db.r7g.12xlarge": {
    "Aurora PostgreSQL": 6.633,
    "Aurora MySQL": 6.633,
    "PostgreSQL": 5.738,
    "MariaDB": 5.738,
    "MySQL": 5.738
  },
  "db.r8g.8xlarge": {
    "PostgreSQL": 3.824,
    "Aurora MySQL": 4.416,
    "Aurora PostgreSQL": 4.416,
    "MariaDB": 3.824,
    "MySQL": 3.824
  },
  "db.r6g.16xlarge": {
    "Aurora MySQL": 10.798,
    "MariaDB": 6.874,
    "Aurora PostgreSQL": 8.306,
    "MySQL": 6.874,
    "PostgreSQL": 7.194
  },
  "db.x2iedn.xlarge": {
    "MySQL": 1.902,
    "Db2": 1.902,
    "SQL Server": 3.3878,
    "Oracle": 1.902,
    "PostgreSQL": 1.902,
    "MariaDB": 1.902
  },
  "db.m5.large": {
    "PostgreSQL": 0.178,
    "SQL Server": 0.977,
    "Oracle (on-premises for Outposts)": 0.0945,
    "SQL Server (on-premise for Outpost)": 0.881,
    "Oracle": 0.171,
    "MySQL (on-premise for Outpost)": 0.075,
    "MariaDB": 0.171,
    "PostgreSQL (on-premise for Outpost)": 0.082,
    "MySQL": 0.171
  },
  "db.r7g.2xlarge": {
    "PostgreSQL": 0.956,
    "MariaDB": 0.956,
    "MySQL": 0.956,
    "Aurora MySQL": 1.106,
    "Aurora PostgreSQL": 1.106
  },
  "db.r8a.4xlarge": {
    "SQL Server": 2.3019
  },
  "db.m6id.metal": {
    "Oracle": 10.752
  },
  "db.m8gd.8xlarge": {
    "MariaDB": 3.1616,
    "PostgreSQL": 3.1616,
    "MySQL": 3.1616
  },
  "db.r5.8xlarge": {
    "SQL Server": 20.008,
    "MySQL (on-premise for Outpost)": 1.824,
    "Oracle": 3.728,
    "SQL Server (on-premise for Outpost)": 10.144,
    "PostgreSQL": 4,
    "Aurora MySQL": 6.032,
    "Oracle (on-premises for Outposts)": 1.984,
    "Aurora PostgreSQL": 6.032,
    "PostgreSQL (on-premise for Outpost)": 1.984,
    "MySQL": 3.84,
    "MariaDB": 3.84
  },
  "db.r7i.16xlarge": {
    "Aurora MySQL": 9.28,
    "Oracle": 8,
    "MySQL": 8,
    "Aurora PostgreSQL": 12.064,
    "SQL Server": 8,
    "Oracle (on-premises for Outposts)": 4.1664,
    "Db2": 8,
    "PostgreSQL": 8,
    "PostgreSQL (on-premise for Outpost)": 3.968,
    "MariaDB": 8
  },
  "db.m6g.16xlarge": {
    "PostgreSQL": 5.088,
    "MariaDB": 4.864,
    "MySQL": 4.864
  },
  "db.r5b.xlarge": {
    "Oracle": 0.551,
    "SQL Server": 0.963,
    "PostgreSQL": 0.592,
    "MySQL": 0.592,
    "MariaDB": 0.592
  },
  "db.m6id.24xlarge": {
    "MySQL": 10.761,
    "PostgreSQL": 10.761,
    "Oracle": 10.752,
    "MariaDB": 10.761
  },
  "db.x2g.xlarge": {
    "MySQL": 0.652,
    "PostgreSQL": 0.652,
    "Aurora MySQL": 0.98,
    "Aurora PostgreSQL": 0.98,
    "MariaDB": 0.652
  },
  "db.t3.large": {
    "Db2": 0.145,
    "SQL Server": 0.232,
    "Oracle": 0.136,
    "Aurora MySQL": 0.213,
    "MariaDB": 0.136,
    "Aurora PostgreSQL": 0.164,
    "PostgreSQL": 0.145,
    "MySQL": 0.136
  },
  "db.x2iedn.32xlarge": {
    "PostgreSQL": 60.864,
    "MariaDB": 60.864,
    "Db2": 60.864,
    "Oracle": 60.864,
    "MySQL": 60.864,
    "SQL Server": 108.4226
  },
  "db.x2g.8xlarge": {
    "PostgreSQL": 5.216,
    "Aurora MySQL": 6.032,
    "Aurora PostgreSQL": 7.842,
    "MariaDB": 5.216,
    "MySQL": 5.216
  },
  "db.r6idn.2xlarge": {
    "Db2": 1.552,
    "MySQL": 1.551,
    "MariaDB": 1.551,
    "PostgreSQL": 1.551
  },
  "db.r8i.large": {
    "Oracle": 0.482,
    "SQL Server": 0.25
  },
  "db.r8gd.16xlarge": {
    "Aurora PostgreSQL": 12.9792,
    "PostgreSQL": 8.736,
    "MySQL": 8.736,
    "MariaDB": 8.736
  },
  "db.r6i.2xlarge": {
    "Aurora MySQL": 1.16,
    "Db2": 1,
    "SQL Server": 5.002,
    "Oracle": 0.932,
    "Aurora PostgreSQL": 1.16,
    "MariaDB": 0.96,
    "PostgreSQL": 1,
    "MySQL": 0.96
  },
  "db.x2iedn.4xlarge": {
    "Db2": 7.608,
    "PostgreSQL": 7.608,
    "Oracle": 7.608,
    "MySQL": 7.608,
    "MariaDB": 7.608,
    "SQL Server": 13.5532
  },
  "db.r7g.8xlarge": {
    "Aurora PostgreSQL": 5.749,
    "Aurora MySQL": 5.749,
    "MySQL": 3.825,
    "PostgreSQL": 3.825,
    "MariaDB": 3.825
  },
  "db.m8i.metal-48xl": {
    "Oracle": 13.46
  },
  "db.r8g.xlarge": {
    "Aurora MySQL": 0.552,
    "MySQL": 0.478,
    "MariaDB": 0.478,
    "Aurora PostgreSQL": 0.718,
    "PostgreSQL": 0.478
  },
  "db.m6in.16xlarge": {
    "Db2": 8.262,
    "MariaDB": 8.262,
    "Oracle": 8.256,
    "MySQL": 8.262,
    "PostgreSQL": 8.262
  },
  "db.m8gd.xlarge": {
    "PostgreSQL": 0.3952,
    "MySQL": 0.3952,
    "MariaDB": 0.3952
  },
  "db.m6i.16xlarge": {
    "MariaDB": 5.472,
    "Db2": 5.696,
    "SQL Server": 37.376,
    "Oracle": 5.472,
    "MySQL": 5.472,
    "PostgreSQL": 5.696
  },
  "db.m7g.12xlarge": {
    "MySQL": 4.044,
    "PostgreSQL": 4.044,
    "MariaDB": 4.044
  },
  "db.r6i.2xlarge.tpc2.mem8x": {
    "Oracle": 7.456
  },
  "db.m6idn.16xlarge": {
    "PostgreSQL": 9.44,
    "MariaDB": 9.44,
    "Db2": 9.44,
    "MySQL": 9.44
  },
  "db.r7i.2xlarge.tpc2.mem8x": {
    "Oracle": 8
  },
  "db.m7i.24xlarge": {
    "PostgreSQL (on-premise for Outpost)": 3.936,
    "MariaDB": 8.544,
    "MySQL": 8.544,
    "Db2": 8.544,
    "SQL Server": 8.544,
    "Oracle (on-premises for Outposts)": 4.7616,
    "Oracle": 8.544,
    "PostgreSQL": 8.544
  },
  "db.m6in.24xlarge": {
    "Db2": 12.394,
    "PostgreSQL": 12.394,
    "Oracle": 12.384,
    "MariaDB": 12.394,
    "MySQL": 12.394
  },
  "db.r7i.xlarge.tpc2.mem4x": {
    "Oracle": 2
  },
  "db.r6idn.32xlarge": {
    "MariaDB": 24.81,
    "Db2": 24.81,
    "MySQL": 24.81,
    "PostgreSQL": 24.81
  },
  "db.m9g.12xlarge": {
    "PostgreSQL": 4.395,
    "MariaDB": 4.395,
    "MySQL": 4.395
  },
  "db.r7i.12xlarge": {
    "SQL Server": 6,
    "MariaDB": 6,
    "MySQL": 6,
    "PostgreSQL (on-premise for Outpost)": 2.976,
    "Db2": 6,
    "Oracle": 6,
    "Aurora MySQL": 6.96,
    "Aurora PostgreSQL": 9.048,
    "PostgreSQL": 6,
    "Oracle (on-premises for Outposts)": 3.1248
  },
  "db.m8i.4xlarge": {
    "Oracle": 3.504,
    "SQL Server": 1.424
  },
  "db.r6i.xlarge": {
    "MySQL": 0.48,
    "Aurora MySQL": 0.58,
    "SQL Server": 1.52,
    "Oracle": 0.466,
    "Db2": 0.5,
    "MariaDB": 0.48,
    "PostgreSQL": 0.5,
    "Aurora PostgreSQL": 0.58
  },
  "db.m7i.metal-48xl": {
    "Oracle": 12.816
  },
  "db.m6id.4xlarge": {
    "Oracle": 1.792,
    "MySQL": 1.794,
    "MariaDB": 1.794,
    "PostgreSQL": 1.794
  },
  "db.m8a.large": {
    "SQL Server": 0.2047
  },
  "db.m8g.large": {
    "MySQL": 0.168,
    "PostgreSQL": 0.168,
    "MariaDB": 0.168
  },
  "db.r8g.48xlarge": {
    "Aurora PostgreSQL": 26.496,
    "MariaDB": 22.944,
    "Aurora MySQL": 26.496,
    "PostgreSQL": 22.944,
    "MySQL": 22.944
  },
  "db.x2iedn.24xlarge": {
    "SQL Server": 81.3167,
    "Oracle": 45.648,
    "Db2": 45.648,
    "PostgreSQL": 45.648,
    "MySQL": 45.648,
    "MariaDB": 45.648
  },
  "db.m7i.2xlarge": {
    "MariaDB": 0.712,
    "SQL Server": 0.712,
    "Db2": 0.712,
    "Oracle (on-premises for Outposts)": 0.3968,
    "Oracle": 0.712,
    "PostgreSQL (on-premise for Outpost)": 0.328,
    "MySQL": 0.712,
    "MySQL (on-premise for Outpost)": 0.328,
    "PostgreSQL": 0.712
  },
  "db.z1d.12xlarge": {
    "SQL Server": 32.074,
    "Oracle": 8.208
  },
  "db.m7i.4xlarge": {
    "PostgreSQL": 1.424,
    "MySQL (on-premise for Outpost)": 0.656,
    "Oracle (on-premises for Outposts)": 0.7936,
    "MariaDB": 1.424,
    "SQL Server": 1.424,
    "Db2": 1.424,
    "MySQL": 1.424,
    "PostgreSQL (on-premise for Outpost)": 0.656,
    "Oracle": 1.424
  },
  "db.r6i.4xlarge": {
    "SQL Server": 6.08,
    "MySQL": 1.92,
    "Aurora MySQL": 3.016,
    "Aurora PostgreSQL": 3.016,
    "Oracle": 3.856,
    "Db2": 2,
    "PostgreSQL": 2,
    "MariaDB": 1.92
  },
  "db.r5b.4xlarge.tpc2.mem2x": {
    "Oracle": 4.41
  },
  "db.r5d.large": {
    "SQL Server": 1.181,
    "PostgreSQL": 0.286,
    "MySQL": 0.286,
    "MariaDB": 0.286,
    "Oracle": 0.266
  },
  "db.x2iedn.8xlarge": {
    "MariaDB": 15.216,
    "Db2": 15.216,
    "MySQL": 15.216,
    "SQL Server": 21.054,
    "PostgreSQL": 15.216,
    "Oracle": 15.216
  },
  "db.r8i.2xlarge": {
    "SQL Server": 1,
    "Oracle": 1.928
  },
  "db.t3.medium": {
    "Db2": 0.072,
    "MySQL": 0.068,
    "Aurora MySQL": 0.082,
    "Oracle": 0.068,
    "PostgreSQL": 0.072,
    "Aurora PostgreSQL": 0.107,
    "SQL Server": 0.166,
    "MariaDB": 0.068
  },
  "db.m6i.metal": {
    "Oracle": 8.208
  },
  "db.m5.16xlarge": {
    "MySQL (on-premise for Outpost)": 2.4,
    "MariaDB": 5.47,
    "SQL Server (on-premise for Outpost)": 34.308,
    "PostgreSQL": 5.696,
    "PostgreSQL (on-premise for Outpost)": 2.624,
    "MySQL": 5.47,
    "SQL Server": 37.376,
    "Oracle": 5.472,
    "Oracle (on-premises for Outposts)": 3.024
  },
  "db.r6gd.8xlarge": {
    "PostgreSQL": 4.114,
    "MySQL": 4.114,
    "Aurora PostgreSQL": 4.992,
    "MariaDB": 4.114
  },
  "db.r7i.2xlarge.tpc2.mem4x": {
    "Oracle": 4
  },
  "db.r6in.8xlarge": {
    "Db2": 5.534,
    "MySQL": 5.534,
    "PostgreSQL": 5.534,
    "Oracle": 5.536,
    "MariaDB": 5.534
  },
  "db.r8gd.12xlarge": {
    "MySQL": 6.552,
    "PostgreSQL": 6.552,
    "MariaDB": 6.552,
    "Aurora PostgreSQL": 7.488
  },
  "db.x1e.xlarge": {
    "SQL Server": 2.472,
    "Oracle": 1.4011
  },
  "db.r5.16xlarge": {
    "Aurora MySQL": 9.28,
    "MySQL": 7.68,
    "MariaDB": 7.68,
    "Aurora PostgreSQL": 12.064,
    "MySQL (on-premise for Outpost)": 3.648,
    "SQL Server (on-premise for Outpost)": 35.984,
    "PostgreSQL": 8,
    "Oracle (on-premises for Outposts)": 3.968,
    "Oracle": 7.456,
    "SQL Server": 40.016,
    "PostgreSQL (on-premise for Outpost)": 3.968
  },
  "db.m8i.8xlarge": {
    "SQL Server": 2.848,
    "Oracle": 2.99
  },
  "db.r8gd.large": {
    "MySQL": 0.273,
    "MariaDB": 0.273,
    "PostgreSQL": 0.273
  },
  "db.r7i.8xlarge": {
    "SQL Server": 4,
    "Aurora PostgreSQL": 4.64,
    "PostgreSQL (on-premise for Outpost)": 1.984,
    "PostgreSQL": 4,
    "Oracle": 4,
    "Oracle (on-premises for Outposts)": 2.0832,
    "MariaDB": 4,
    "Aurora MySQL": 4.64,
    "Db2": 4,
    "MySQL (on-premise for Outpost)": 1.984,
    "MySQL": 4
  },
  "db.r7i.48xlarge": {
    "Aurora PostgreSQL": 36.192,
    "SQL Server": 24,
    "Oracle (on-premises for Outposts)": 12.4992,
    "Db2": 24,
    "PostgreSQL (on-premise for Outpost)": 11.904,
    "MySQL": 24,
    "PostgreSQL": 24,
    "Aurora MySQL": 36.192,
    "Oracle": 24,
    "MariaDB": 24
  },
  "db.x2g.large": {
    "PostgreSQL": 0.326,
    "Aurora MySQL": 0.49,
    "MariaDB": 0.326,
    "MySQL": 0.326,
    "Aurora PostgreSQL": 0.49
  },
  "db.r8g.12xlarge": {
    "MariaDB": 5.736,
    "PostgreSQL": 5.736,
    "MySQL": 5.736,
    "Aurora PostgreSQL": 8.616,
    "Aurora MySQL": 6.624
  },
  "db.r6i.24xlarge": {
    "Aurora MySQL": 13.92,
    "SQL Server": 17.856,
    "MariaDB": 11.52,
    "Oracle": 11.184,
    "Aurora PostgreSQL": 13.92,
    "MySQL": 11.52,
    "PostgreSQL": 12,
    "Db2": 12
  },
  "db.x2g.4xlarge": {
    "MySQL": 2.608,
    "PostgreSQL": 2.608,
    "Aurora PostgreSQL": 3.921,
    "MariaDB": 2.608,
    "Aurora MySQL": 3.921
  },
  "db.r8i.12xlarge": {
    "SQL Server": 6,
    "Oracle": 6.3
  },
  "db.x1e.16xlarge": {
    "SQL Server": 39.547,
    "Oracle": 22.4179
  },
  "db.m6id.2xlarge": {
    "Oracle": 0.896,
    "MySQL": 0.897,
    "MariaDB": 0.897,
    "PostgreSQL": 0.897
  },
  "db.x2iezn.12xlarge": {
    "Oracle": 18.215
  },
  "db.r8i.8xlarge": {
    "SQL Server": 4,
    "Oracle": 4.2
  },
  "db.r5.xlarge.tpc2.mem2x": {
    "Oracle": 0.932
  },
  "db.r6id.16xlarge": {
    "PostgreSQL": 9.543,
    "MariaDB": 9.543,
    "Oracle": 9.536,
    "MySQL": 9.543
  },
  "db.r6i.metal": {
    "Oracle": 11.184
  },
  "db.r8i.96xlarge": {
    "SQL Server": 48
  },
  "db.m7g.2xlarge": {
    "PostgreSQL": 0.674,
    "MySQL": 0.674,
    "MariaDB": 0.674
  },
  "db.m5d.4xlarge": {
    "MySQL": 1.676,
    "Oracle": 1.61,
    "PostgreSQL": 1.676,
    "SQL Server": 2.388,
    "MariaDB": 1.676
  },
  "db.x2iezn.metal": {
    "Oracle": 13.661
  },
  "db.r6id.32xlarge": {
    "MySQL": 19.086,
    "MariaDB": 19.086,
    "PostgreSQL": 19.086,
    "Oracle": 19.072,
    "Aurora PostgreSQL": 28.954
  },
  "db.m8a.8xlarge": {
    "SQL Server": 3.2757
  },
  "db.r6in.4xlarge": {
    "PostgreSQL": 2.767,
    "Oracle": 2.768,
    "Db2": 2.768,
    "MySQL": 2.767,
    "MariaDB": 2.767
  },
  "db.m6in.32xlarge": {
    "Db2": 16.525,
    "Oracle": 16.512,
    "MariaDB": 16.525,
    "PostgreSQL": 16.525,
    "MySQL": 16.525
  },
  "db.m8i.96xlarge": {
    "SQL Server": 34.176
  },
  "db.m8a.4xlarge": {
    "SQL Server": 1.6379
  },
  "db.r5.large.tpc1.mem2x": {
    "Oracle": 0.466
  },
  "db.r6id.12xlarge": {
    "PostgreSQL": 7.157,
    "MySQL": 7.157,
    "MariaDB": 7.157,
    "Oracle": 7.152
  },
  "db.m8i.32xlarge": {
    "SQL Server": 11.392,
    "Oracle": 11.96
  },
  "db.m8gd.2xlarge": {
    "PostgreSQL": 0.7904,
    "MySQL": 0.7904,
    "MariaDB": 0.7904
  },
  "db.r6g.4xlarge": {
    "MariaDB": 1.718,
    "Aurora MySQL": 2.699,
    "MySQL": 1.718,
    "PostgreSQL": 1.798,
    "Aurora PostgreSQL": 2.076
  },
  "db.m5.8xlarge": {
    "MariaDB": 2.74,
    "PostgreSQL (on-premise for Outpost)": 1.312,
    "SQL Server": 9.792,
    "SQL Server (on-premise for Outpost)": 17.154,
    "MySQL (on-premise for Outpost)": 1.2,
    "Oracle": 2.736,
    "MySQL": 2.74,
    "Oracle (on-premises for Outposts)": 1.512,
    "PostgreSQL": 2.848
  },
  "db.m5d.16xlarge": {
    "PostgreSQL": 6.705,
    "SQL Server": 20.648,
    "MySQL": 6.705,
    "MariaDB": 6.705,
    "Oracle": 6.441
  },
  "db.r6in.2xlarge": {
    "PostgreSQL": 1.384,
    "Db2": 1.384,
    "Oracle": 1.384,
    "MySQL": 1.384,
    "MariaDB": 1.384
  },
  "db.m6g.8xlarge": {
    "PostgreSQL": 2.544,
    "MariaDB": 2.432,
    "MySQL": 2.432
  },
  "db.x1.16xlarge": {
    "Oracle": 11.2,
    "SQL Server": 28.533
  },
  "db.m6i.8xlarge": {
    "MariaDB": 2.736,
    "SQL Server": 4.8,
    "MySQL": 2.736,
    "Db2": 2.848,
    "Oracle": 2.736,
    "PostgreSQL": 2.848
  },
  "db.m7i.12xlarge": {
    "SQL Server": 4.272,
    "PostgreSQL": 4.272,
    "Oracle": 4.272,
    "Db2": 4.272,
    "PostgreSQL (on-premise for Outpost)": 1.968,
    "MariaDB": 4.272,
    "MySQL": 4.272,
    "Oracle (on-premises for Outposts)": 2.3808
  },
  "db.m6i.24xlarge": {
    "Db2": 8.544,
    "SQL Server": 56.064,
    "PostgreSQL": 8.544,
    "MySQL": 8.208,
    "MariaDB": 8.208,
    "Oracle": 8.208
  },
  "db.m6gd.xlarge": {
    "PostgreSQL": 0.373,
    "MySQL": 0.373,
    "MariaDB": 0.373
  },
  "db.x2m.24xlarge": {
    "SQL Server": 45.648
  },
  "db.t4g.medium": {
    "MySQL": 0.065,
    "Aurora MySQL": 0.095,
    "PostgreSQL": 0.065,
    "Aurora PostgreSQL": 0.095,
    "MariaDB": 0.065
  },
  "db.m8g.48xlarge": {
    "PostgreSQL": 16.128,
    "MySQL": 16.128,
    "MariaDB": 16.128
  },
  "db.r6i.8xlarge.tpc2.mem4x": {
    "Oracle": 14.912
  },
  "db.x2g.16xlarge": {
    "MySQL": 10.432,
    "Aurora MySQL": 12.064,
    "PostgreSQL": 10.432,
    "Aurora PostgreSQL": 12.064,
    "MariaDB": 10.432
  },
  "db.r6idn.16xlarge": {
    "Db2": 12.405,
    "MySQL": 12.405,
    "PostgreSQL": 12.405,
    "MariaDB": 12.405
  },
  "db.m8a.xlarge": {
    "SQL Server": 0.4094
  },
  "db.m6g.4xlarge": {
    "MySQL": 1.216,
    "MariaDB": 1.216,
    "PostgreSQL": 1.272
  },
  "db.m6i.large": {
    "SQL Server": 0.977,
    "Db2": 0.178,
    "MariaDB": 0.171,
    "MySQL": 0.171,
    "PostgreSQL": 0.178,
    "Oracle": 0.171
  },
  "db.r6in.large": {
    "PostgreSQL": 0.346,
    "Db2": 0.346,
    "MariaDB": 0.346,
    "MySQL": 0.346,
    "Oracle": 0.346
  },
  "db.r6id.24xlarge": {
    "Oracle": 14.304,
    "MariaDB": 14.314,
    "MySQL": 14.314,
    "PostgreSQL": 14.314,
    "Aurora PostgreSQL": 21.715
  },
  "db.x2iedn.metal": {
    "Oracle": 45.648
  },
  "db.m5d.2xlarge": {
    "MariaDB": 0.838,
    "PostgreSQL": 0.838,
    "SQL Server": 1.194,
    "MySQL": 0.838,
    "Oracle": 0.805
  },
  "db.x2iezn.2xlarge": {
    "Oracle": 3.036
  },
  "db.m8gd.16xlarge": {
    "MariaDB": 6.3232,
    "PostgreSQL": 6.3232,
    "MySQL": 6.3232
  },
  "db.m6in.8xlarge": {
    "PostgreSQL": 4.131,
    "Db2": 4.128,
    "Oracle": 4.128,
    "MySQL": 4.131,
    "MariaDB": 4.131
  },
  "db.r6i.4xlarge.tpc2.mem2x": {
    "Oracle": 3.728
  },
  "db.r8a.16xlarge": {
    "SQL Server": 9.2073
  },
  "db.x2iedn.16xlarge": {
    "Db2": 30.432,
    "MySQL": 30.432,
    "MariaDB": 30.432,
    "PostgreSQL": 30.432,
    "Oracle": 30.432,
    "SQL Server": 54.2108
  },
  "db.m6idn.4xlarge": {
    "Db2": 2.36,
    "PostgreSQL": 2.36,
    "MySQL": 2.36,
    "MariaDB": 2.36
  },
  "db.r5.2xlarge.tpc1.mem2x": {
    "Oracle": 1.864
  },
  "db.m5.24xlarge": {
    "MySQL (on-premise for Outpost)": 3.6,
    "PostgreSQL": 8.544,
    "PostgreSQL (on-premise for Outpost)": 3.936,
    "MySQL": 8.208,
    "SQL Server": 56.064,
    "Oracle (on-premises for Outposts)": 4.536,
    "SQL Server (on-premise for Outpost)": 24.768,
    "Oracle": 8.208,
    "MariaDB": 8.208
  },
  "db.r8g.24xlarge": {
    "MariaDB": 11.472,
    "PostgreSQL": 11.472,
    "Aurora MySQL": 17.232,
    "MySQL": 11.472,
    "Aurora PostgreSQL": 13.248
  },
  "db.r6i.8xlarge.tpc2.mem3x": {
    "Oracle": 11.184
  },
  "db.m6i.4xlarge": {
    "MySQL": 1.368,
    "MariaDB": 1.368,
    "SQL Server": 2.247,
    "Db2": 1.424,
    "PostgreSQL": 1.424,
    "Oracle": 1.368
  },
  "db.r5d.24xlarge": {
    "MariaDB": 13.714,
    "SQL Server": 37.699,
    "MySQL": 13.714,
    "PostgreSQL": 13.714,
    "Oracle": 12.783
  },
  "db.r8gd.48xlarge": {
    "MySQL": 26.208,
    "PostgreSQL": 26.208,
    "Aurora PostgreSQL": 29.952,
    "MariaDB": 26.208
  },
  "db.r8gd.24xlarge": {
    "Aurora PostgreSQL": 14.976,
    "MySQL": 13.104,
    "PostgreSQL": 13.104,
    "MariaDB": 13.104
  },
  "db.m9g.8xlarge": {
    "MySQL": 2.93,
    "PostgreSQL": 2.93,
    "MariaDB": 2.93
  },
  "db.r8gd.4xlarge": {
    "Aurora PostgreSQL": 3.2448,
    "MySQL": 2.184,
    "MariaDB": 2.184,
    "PostgreSQL": 2.184
  },
  "db.r6gd.xlarge": {
    "Aurora PostgreSQL": 0.624,
    "MariaDB": 0.514,
    "MySQL": 0.514,
    "PostgreSQL": 0.514
  },
  "db.r8gd.xlarge": {
    "Aurora PostgreSQL": 0.624,
    "MariaDB": 0.546,
    "PostgreSQL": 0.546,
    "MySQL": 0.546
  },
  "db.r6in.16xlarge": {
    "MySQL": 11.069,
    "Oracle": 11.072,
    "Db2": 11.069,
    "PostgreSQL": 11.069,
    "MariaDB": 11.069
  },
  "db.m6gd.4xlarge": {
    "MySQL": 1.493,
    "MariaDB": 1.493,
    "PostgreSQL": 1.493
  },
  "db.m6in.4xlarge": {
    "Oracle": 2.064,
    "Db2": 2.064,
    "MariaDB": 2.066,
    "MySQL": 2.066,
    "PostgreSQL": 2.066
  },
  "db.t4g.large": {
    "MySQL": 0.129,
    "MariaDB": 0.129,
    "Aurora PostgreSQL": 0.146,
    "Aurora MySQL": 0.146,
    "PostgreSQL": 0.129
  },
  "db.m8gd.48xlarge": {
    "MariaDB": 18.9696,
    "MySQL": 18.9696,
    "PostgreSQL": 18.9696
  },
  "db.r8i.24xlarge": {
    "SQL Server": 12,
    "Oracle": 12.6
  },
  "db.r6i.large.tpc1.mem2x": {
    "Oracle": 0.466
  },
  "db.r5.4xlarge.tpc2.mem4x": {
    "Oracle": 7.456
  },
  "db.r6gd.12xlarge": {
    "Aurora PostgreSQL": 7.488,
    "PostgreSQL": 6.171,
    "MySQL": 6.171,
    "MariaDB": 6.171
  },
  "db.m6gd.2xlarge": {
    "MariaDB": 0.747,
    "PostgreSQL": 0.747,
    "MySQL": 0.747
  },
  "db.r6idn.large": {
    "Db2": 0.388,
    "PostgreSQL": 0.388,
    "MariaDB": 0.388,
    "MySQL": 0.388
  },
  "db.r6id.2xlarge": {
    "MariaDB": 1.193,
    "Oracle": 1.192,
    "MySQL": 1.193,
    "PostgreSQL": 1.193
  },
  "db.r8i.metal-96xl": {
    "Oracle": 37.80136054
  },
  "db.r6id.xlarge": {
    "PostgreSQL": 0.596,
    "Oracle": 0.596,
    "MariaDB": 0.596,
    "MySQL": 0.596
  },
  "db.r6idn.xlarge": {
    "Db2": 0.775,
    "MariaDB": 0.775,
    "PostgreSQL": 0.775,
    "MySQL": 0.775
  },
  "db.x1.32xlarge": {
    "SQL Server": 57.067,
    "Oracle": 22.4
  },
  "db.x2g.2xlarge": {
    "Aurora PostgreSQL": 1.96,
    "Aurora MySQL": 1.508,
    "PostgreSQL": 1.304,
    "MariaDB": 1.304,
    "MySQL": 1.304
  },
  "db.m8g.xlarge": {
    "MariaDB": 0.336,
    "MySQL": 0.336,
    "PostgreSQL": 0.336
  },
  "db.m7i.metal-24xl": {
    "Oracle": 6.408
  },
  "db.m8i.48xlarge": {
    "Oracle": 17.94,
    "SQL Server": 17.088
  },
  "db.r5b.8xlarge": {
    "PostgreSQL": 4.736,
    "Oracle": 4.41,
    "SQL Server": 12.698,
    "MariaDB": 4.736,
    "MySQL": 4.736
  },
  "db.x2iezn.6xlarge": {
    "Oracle": 9.107
  },
  "db.t3.micro": {
    "SQL Server": 0.022,
    "PostgreSQL": 0.018,
    "MySQL": 0.017,
    "MariaDB": 0.017
  },
  "db.r5b.16xlarge": {
    "Oracle": 8.821,
    "SQL Server": 25.397,
    "PostgreSQL": 9.472,
    "MySQL": 9.472,
    "MariaDB": 9.472
  },
  "db.r8g.16xlarge": {
    "MariaDB": 7.648,
    "Aurora PostgreSQL": 11.488,
    "Aurora MySQL": 8.832,
    "MySQL": 7.648,
    "PostgreSQL": 7.648
  },
  "db.m8g.2xlarge": {
    "MariaDB": 0.672,
    "PostgreSQL": 0.672,
    "MySQL": 0.672
  },
  "db.r6in.32xlarge": {
    "Db2": 22.138,
    "Oracle": 22.144,
    "MySQL": 22.138,
    "PostgreSQL": 22.138,
    "MariaDB": 22.138
  },
  "db.m6g.2xlarge": {
    "PostgreSQL": 0.636,
    "MySQL": 0.608,
    "MariaDB": 0.608
  },
  "db.r5.2xlarge.tpc2.mem4x": {
    "Oracle": 3.728
  },
  "db.r8a.12xlarge": {
    "SQL Server": 6.9054
  },
  "db.x2m.2xlarge": {
    "SQL Server": 3.804
  },
  "db.m6id.large": {
    "Oracle": 0.224,
    "MariaDB": 0.224,
    "PostgreSQL": 0.224,
    "MySQL": 0.224
  },
  "db.m9g.2xlarge": {
    "MariaDB": 0.732,
    "MySQL": 0.732,
    "PostgreSQL": 0.732
  },
  "db.r6gd.large": {
    "MySQL": 0.257,
    "MariaDB": 0.257,
    "PostgreSQL": 0.257
  },
  "db.t4g.micro": {
    "PostgreSQL": 0.016,
    "MariaDB": 0.016,
    "MySQL": 0.016
  },
  "db.m8i.large": {
    "SQL Server": 0.178,
    "Oracle": 0.19
  },
  "db.m9g.4xlarge": {
    "PostgreSQL": 1.465,
    "MariaDB": 1.465,
    "MySQL": 1.465
  },
  "db.r6i.2xlarge.tpc2.mem4x": {
    "Oracle": 3.728
  },
  "db.r5d.8xlarge": {
    "Oracle": 4.261,
    "MariaDB": 4.571,
    "SQL Server": 20.509,
    "MySQL": 4.571,
    "PostgreSQL": 4.571
  },
  "db.m6gd.large": {
    "MariaDB": 0.187,
    "PostgreSQL": 0.187,
    "MySQL": 0.187
  },
  "db.m8gd.24xlarge": {
    "MySQL": 9.4848,
    "PostgreSQL": 9.4848,
    "MariaDB": 9.4848
  },
  "db.r6in.12xlarge": {
    "Oracle": 8.304,
    "MariaDB": 8.302,
    "MySQL": 8.302,
    "Db2": 8.302,
    "PostgreSQL": 8.302
  },
  "db.x2idn.24xlarge": {
    "Oracle": 16.8
  },
  "db.m6idn.32xlarge": {
    "Db2": 18.88,
    "MariaDB": 18.88,
    "PostgreSQL": 18.88,
    "MySQL": 18.88
  },
  "db.m7g.4xlarge": {
    "PostgreSQL": 1.348,
    "MySQL": 1.348,
    "MariaDB": 1.348
  },
  "db.r5b.2xlarge.tpc2.mem8x": {
    "Oracle": 8.821
  },
  "db.m6id.16xlarge": {
    "MySQL": 7.174,
    "PostgreSQL": 7.174,
    "Oracle": 7.168,
    "MariaDB": 7.174
  },
  "db.r6i.4xlarge.tpc2.mem3x": {
    "Oracle": 5.592
  },
  "db.m8g.8xlarge": {
    "MariaDB": 2.688,
    "MySQL": 2.688,
    "PostgreSQL": 2.688
  },
  "db.r6i.12xlarge": {
    "Db2": 6,
    "Aurora MySQL": 6.96,
    "Aurora PostgreSQL": 9.048,
    "SQL Server": 8.928,
    "MariaDB": 5.76,
    "PostgreSQL": 6,
    "MySQL": 5.76,
    "Oracle": 5.592
  },
  "db.r7g.xlarge": {
    "PostgreSQL": 0.478,
    "Aurora PostgreSQL": 0.553,
    "MariaDB": 0.478,
    "Aurora MySQL": 0.719,
    "MySQL": 0.478
  },
  "db.r6id.8xlarge": {
    "Oracle": 4.768,
    "PostgreSQL": 4.771,
    "MySQL": 4.771,
    "MariaDB": 4.771
  },
  "db.r6i.6xlarge.tpc2.mem4x": {
    "Oracle": 11.184
  },
  "db.x1e.32xlarge": {
    "SQL Server": 79.094,
    "Oracle": 44.8358
  },
  "db.r7i.8xlarge.tpc2.mem2x": {
    "Oracle": 8
  },
  "db.z1d.3xlarge": {
    "SQL Server": 8.018,
    "Oracle": 2.052
  },
  "db.m6idn.8xlarge": {
    "Db2": 4.72,
    "MySQL": 4.72,
    "PostgreSQL": 4.72,
    "MariaDB": 4.72
  },
  "db.x2g.12xlarge": {
    "MySQL": 7.824,
    "Aurora MySQL": 9.048,
    "Aurora PostgreSQL": 11.762,
    "MariaDB": 7.824,
    "PostgreSQL": 7.824
  },
  "db.r8g.2xlarge": {
    "Aurora MySQL": 1.436,
    "Aurora PostgreSQL": 1.104,
    "MySQL": 0.956,
    "PostgreSQL": 0.956,
    "MariaDB": 0.956
  },
  "db.r5b.6xlarge.tpc2.mem4x": {
    "Oracle": 13.231
  },
  "db.m8a.16xlarge": {
    "SQL Server": 6.5514
  },
  "db.r5b.12xlarge": {
    "SQL Server": 30.92,
    "Oracle": 6.615,
    "PostgreSQL": 7.104,
    "MariaDB": 7.104,
    "MySQL": 7.104
  },
  "db.m6g.xlarge": {
    "PostgreSQL": 0.318,
    "MariaDB": 0.304,
    "MySQL": 0.304
  },
  "db.r6idn.12xlarge": {
    "Db2": 9.304,
    "PostgreSQL": 9.304,
    "MySQL": 9.304,
    "MariaDB": 9.304
  },
  "db.r6g.8xlarge": {
    "MySQL": 3.437,
    "Aurora MySQL": 5.399,
    "Aurora PostgreSQL": 4.153,
    "MariaDB": 3.437,
    "PostgreSQL": 3.597
  },
  "db.r6i.4xlarge.tpc2.mem4x": {
    "Oracle": 7.456
  },
  "db.z1d.xlarge": {
    "SQL Server": 1.709,
    "Oracle": 0.683
  },
  "db.m9g.16xlarge": {
    "PostgreSQL": 5.86,
    "MySQL": 5.86,
    "MariaDB": 5.86
  },
  "db.r7g.4xlarge": {
    "MySQL": 1.913,
    "Aurora PostgreSQL": 2.211,
    "Aurora MySQL": 2.874,
    "MariaDB": 1.913,
    "PostgreSQL": 1.913
  },
  "db.r7i.6xlarge.tpc2.mem2x": {
    "Oracle": 6
  },
  "db.m6gd.12xlarge": {
    "MySQL": 4.48,
    "PostgreSQL": 4.48,
    "MariaDB": 4.48
  },
  "db.m8i.16xlarge": {
    "SQL Server": 5.696,
    "Oracle": 5.98
  },
  "db.x2iezn.4xlarge": {
    "Oracle": 6.072
  },
  "db.m7g.8xlarge": {
    "MySQL": 2.696,
    "PostgreSQL": 2.696,
    "MariaDB": 2.696
  },
  "db.r7i.4xlarge.tpc2.mem4x": {
    "Oracle": 8
  },
  "db.r6i.2xlarge.tpc1.mem2x": {
    "Oracle": 1.864
  },
  "db.r6id.metal": {
    "Oracle": 14.304
  },
  "db.z1d.large": {
    "Oracle": 0.342,
    "SQL Server": 1.251
  },
  "db.z1d.2xlarge": {
    "Oracle": 1.368,
    "SQL Server": 5.346
  },
  "db.r6in.metal": {
    "Oracle": 16.608
  },
  "db.r8gd.8xlarge": {
    "PostgreSQL": 4.368,
    "MariaDB": 4.368,
    "MySQL": 4.368,
    "Aurora PostgreSQL": 4.992
  },
  "db.r5b.8xlarge.tpc2.mem3x": {
    "Oracle": 13.231
  },
  "db.r7i.4xlarge.tpc2.mem3x": {
    "Oracle": 6
  },
  "db.r8a.2xlarge": {
    "SQL Server": 1.1508
  },
  "db.r5b.xlarge.tpc2.mem2x": {
    "Oracle": 1.103
  },
  "db.r7i.metal-48xl": {
    "Oracle": 18
  },
  "db.x2m.4xlarge": {
    "SQL Server": 7.608
  },
  "db.m8i.metal-96xl": {
    "Oracle": 26.9136
  },
  "db.x2m.32xlarge": {
    "SQL Server": 60.864
  },
  "db.m8gd.4xlarge": {
    "PostgreSQL": 1.5808,
    "MySQL": 1.5808,
    "MariaDB": 1.5808
  },
  "db.m6gd.8xlarge": {
    "MariaDB": 2.987,
    "MySQL": 2.987,
    "PostgreSQL": 2.987
  },
  "db.m8a.2xlarge": {
    "SQL Server": 0.819
  },
  "db.r5.2xlarge.tpc2.mem8x": {
    "Oracle": 7.456
  },
  "db.r5b.large.tpc1.mem2x": {
    "Oracle": 0.551
  },
  "db.r5b.4xlarge.tpc2.mem3x": {
    "Oracle": 6.615
  },
  "db.x1e.8xlarge": {
    "SQL Server": 26.187,
    "Oracle": 11.209
  },
  "db.m6id.8xlarge": {
    "Oracle": 3.584,
    "PostgreSQL": 3.587,
    "MariaDB": 3.587,
    "MySQL": 3.587
  },
  "db.r6g.xlarge": {
    "PostgreSQL": 0.45,
    "MariaDB": 0.43,
    "MySQL": 0.43,
    "Aurora PostgreSQL": 0.519,
    "Aurora MySQL": 0.519
  },
  "db.m6gd.16xlarge": {
    "PostgreSQL": 5.973,
    "MariaDB": 5.973,
    "MySQL": 5.973
  },
  "db.x2idn.16xlarge": {
    "Oracle": 11.2
  },
  "db.r8i.metal-48xl": {
    "Oracle": 18.9
  },
  "db.r5d.12xlarge": {
    "SQL Server": 30.763,
    "MySQL": 6.857,
    "Oracle": 6.392,
    "MariaDB": 6.857,
    "PostgreSQL": 6.857
  },
  "db.x1e.4xlarge": {
    "SQL Server": 13.094,
    "Oracle": 5.6045
  },
  "db.r5b.2xlarge": {
    "PostgreSQL": 1.184,
    "Oracle": 1.103,
    "SQL Server": 3.175,
    "MariaDB": 1.184,
    "MySQL": 1.184
  },
  "db.r7i.4xlarge.tpc2.mem2x": {
    "Oracle": 4
  },
  "db.m8g.12xlarge": {
    "MySQL": 4.032,
    "PostgreSQL": 4.032,
    "MariaDB": 4.032
  },
  "db.r5.4xlarge.tpc2.mem2x": {
    "Oracle": 3.728
  },
  "db.r5.xlarge.tpc2.mem4x": {
    "Oracle": 1.864
  },
  "db.r5.6xlarge.tpc2.mem4x": {
    "Oracle": 11.184
  },
  "db.m8a.12xlarge": {
    "SQL Server": 4.9136
  },
  "db.x2m.16xlarge": {
    "SQL Server": 30.432
  },
  "db.x2m.xlarge": {
    "SQL Server": 1.902
  },
  "db.r5b.4xlarge.tpc2.mem4x": {
    "Oracle": 8.821
  },
  "db.r7i.metal-24xl": {
    "Oracle": 9
  },
  "db.r7i.3xlarge.tpc2.mem4x": {
    "Oracle": 6
  },
  "db.m6in.metal": {
    "Oracle": 12.384
  },
  "db.r6i.xlarge.tpc2.mem4x": {
    "Oracle": 1.864
  },
  "db.m7g.xlarge": {
    "MySQL": 0.337,
    "PostgreSQL": 0.337,
    "MariaDB": 0.337
  },
  "db.m8g.24xlarge": {
    "MySQL": 8.064,
    "PostgreSQL": 8.064,
    "MariaDB": 8.064
  },
  "db.r6i.xlarge.tpc2.mem2x": {
    "Oracle": 0.932
  },
  "db.r5b.xlarge.tpc2.mem4x": {
    "Oracle": 2.205
  },
  "db.m6id.12xlarge": {
    "Oracle": 5.376,
    "PostgreSQL": 5.381,
    "MariaDB": 5.381,
    "MySQL": 5.381
  },
  "db.x1e.2xlarge": {
    "Oracle": 2.8022,
    "SQL Server": 4.943
  },
  "db.r5.4xlarge.tpc2.mem3x": {
    "Oracle": 5.592
  },
  "db.t4g.small": {
    "PostgreSQL": 0.032,
    "MariaDB": 0.032,
    "MySQL": 0.032
  },
  "db.m7g.16xlarge": {
    "MariaDB": 5.392,
    "MySQL": 5.392,
    "PostgreSQL": 5.392
  },
  "db.m8g.16xlarge": {
    "PostgreSQL": 5.376,
    "MySQL": 5.376,
    "MariaDB": 5.376
  },
  "db.r7i.8xlarge.tpc2.mem3x": {
    "Oracle": 12
  },
  "db.r8a.large": {
    "SQL Server": 0.2878
  },
  "db.r5.8xlarge.tpc2.mem3x": {
    "Oracle": 11.184
  },
  "db.r7i.6xlarge.tpc2.mem4x": {
    "Oracle": 12
  },
  "db.m8gd.12xlarge": {
    "PostgreSQL": 4.7424,
    "MySQL": 4.7424,
    "MariaDB": 4.7424
  },
  "db.r5.12xlarge.tpc2.mem2x": {
    "Oracle": 11.184
  },
  "db.r7i.xlarge.tpc2.mem2x": {
    "Oracle": 1
  },
  "db.x2iezn.8xlarge": {
    "Oracle": 12.143
  },
  "db.x2idn.32xlarge": {
    "Oracle": 22.4
  }
} as Record<string, Record<string, number>>,
  rdsStoragePerGbMonth: 0.115,
  elasticacheHourlyByNode: {
  "cache.r7g.4xlarge": 0.2513,
  "cache.m5.xlarge": 0.0952,
  "cache.r6g.16xlarge": 0.9456,
  "cache.r7g.large": 0.0315,
  "cache.m7g.12xlarge": 0.5429,
  "cache.m7g.xlarge": 0.0454,
  "cache.m5.2xlarge": 0.1912,
  "cache.m7g.2xlarge": 0.0906,
  "cache.r4.2xlarge": 0.728,
  "cache.m6g.large": 0.0215,
  "cache.c7gn.4xlarge": 0.2933,
  "cache.m6g.12xlarge": 0.5122,
  "cache.m6g.2xlarge": 0.0854,
  "cache.m6g.xlarge": 0.0428,
  "cache.r4.large": 0.182,
  "cache.t3.micro": 0.0136,
  "cache.r6gd.2xlarge": 1.248,
  "cache.m7g.8xlarge": 0.362,
  "cache.t4g.medium": 0.052,
  "cache.t4g.small": 0.0256,
  "cache.r6gd.4xlarge": 2.496,
  "cache.r5.24xlarge": 3.456,
  "cache.r6gd.8xlarge": 4.992,
  "cache.m7g.4xlarge": 0.181,
  "cache.m5.4xlarge": 0.3816,
  "cache.r7g.8xlarge": 0.5027,
  "cache.r6g.4xlarge": 0.2364,
  "cache.r6g.large": 0.0297,
  "cache.r5.2xlarge": 0.2864,
  "cache.t3.small": 0.027,
  "cache.r6gd.12xlarge": 7.486,
  "cache.c7gn.xlarge": 0.0733,
  "cache.r7g.12xlarge": 0.7538,
  "cache.r4.16xlarge": 5.824,
  "cache.t3.medium": 0.054,
  "cache.m4.4xlarge": 0.996,
  "cache.r6g.8xlarge": 0.4729,
  "cache.t2.small": 0.027,
  "cache.r7g.xlarge": 0.0629,
  "cache.r4.8xlarge": 2.912,
  "cache.t4g.micro": 0.0128,
  "cache.r5.large": 0.072,
  "cache.m5.large": 0.048,
  "cache.r4.4xlarge": 1.456,
  "cache.m6g.8xlarge": 0.3416,
  "cache.t2.micro": 0.0136,
  "cache.r5.xlarge": 0.1432,
  "cache.m6g.16xlarge": 0.683,
  "cache.c7gn.2xlarge": 0.1466,
  "cache.m5.24xlarge": 2.304,
  "cache.r7g.16xlarge": 1.0053,
  "cache.r6g.12xlarge": 0.7092,
  "cache.t2.medium": 0.054,
  "cache.m5.12xlarge": 1.152,
  "cache.r7g.2xlarge": 0.1257,
  "cache.r5.4xlarge": 0.5728,
  "cache.m4.xlarge": 0.2488,
  "cache.m4.large": 0.1248,
  "cache.c7gn.8xlarge": 0.5865,
  "cache.r6g.xlarge": 0.0592,
  "cache.r6gd.xlarge": 0.6248,
  "cache.c7gn.large": 0.0367,
  "cache.r5.12xlarge": 1.728,
  "cache.r4.xlarge": 0.364,
  "cache.m7g.large": 0.0228,
  "cache.m7g.16xlarge": 0.724,
  "cache.r6gd.16xlarge": 9.9816,
  "cache.r6g.2xlarge": 0.1182,
  "cache.c7gn.12xlarge": 0.8798,
  "cache.m4.2xlarge": 0.498,
  "cache.c7gn.16xlarge": 1.1732,
  "cache.m6g.4xlarge": 0.1708,
  "cache.m4.10xlarge": 2.4896
} as Record<string, number>,
  ebsPerGbMonth: {
  "gp3": 0.08,
  "sc1": 0.015,
  "io1": 0.125,
  "gp2": 0.1,
  "io2": 0.125,
  "st1": 0.045,
  "standard": 0.05
} as Record<string, number>,
  ebsIopsPerMonth: {
  "io2": 0.065,
  "gp3": 0.005,
  "io1": 0.065
} as Record<string, number>,
  s3PerGbMonth: {
  "glacier-instant": 0.004,
  "intelligent-tiering": 0.023,
  "standard": 0.023
} as Record<string, number>,
  lambdaGbSecond: 0.0000166667,
  lambdaRequest: 2e-7,
  dynamoReadRequest: 1.25e-7,
  dynamoWriteRequest: 6.25e-7,
  dynamoRcuHour: 0.00013,
  dynamoWcuHour: 0.00065,
  dynamoStoragePerGbMonth: 0.25,
  natGatewayHourly: 0.045,
  albHourly: 0.0225,
  nlbHourly: 0.0225,
} as const;
